### ISSUE TITLE
Choisir une langue de développement

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#1]
Je pense qu'il faut absolument éviter de mélanger du code avec des noms francais et des noms anglais (song/chant, auteur/author...)

Pour moi, le plus logique serait de garder l'anglais comme langue de code (ce qui n'interdit pas de faire des commentaires en francais)
Les urls devraient aussi utiliser l'anglais (les néophytes ne les regardent pas et les utilisateurs plus avancés comprendront le choix)

**Comment by Luthaf** [comment]
Je suis d'accord, je vais modifier les URL un de ces quatres.

Pour le code, j'avais commencé à l'écrire en français, et puis j'ai traduit tout ce qui me passait sous la main, mais il doit en rester. 
Après, les champs de type verbose_name sont facilement localisables à posteriori, donc je préfère les écrire en français, puis les localiser en anglais plus tard, étant donné que le site est dans un premier temps à destination d'un public français.

**Comment by oliverpool** [comment]
ok (attention, Langage se dit Language en anglais ;-)

**Comment by Luthaf** [comment]
Ok, merci =)

Une question connexe : il est (relativement) facile de traduire les URL. On peut donc penser avoir un site avec des URL de la forme

/en/songs/anonymous/greensleeves -> La page en anglais
/fr/chants/anonymous/greensleeves -> La page en français

/en/user/ -> La page en anglais
/fr/utilisateur/ -> La page en français

Cela vaut-il le coup ? Moi j'aime bien, mais ce n'est pas très important non plus =) Ça permettrai d'écrire dans un premier temps toutes les URLs en français, puis de les traduire ultérieurement en anglais.

**Comment by oliverpool** [comment]
C'est effectivement plus joli, mais je ne suis pas convaincu par rapport au travail occasionné (et je reste persuadé que la plupart des gens se moquent de l'url)

**Comment by Luthaf** [comment]
Ça dépend en fait si le site doit être disponible en plusieurs langues à la fin. 
Si oui, le travail supplémentaire pour les URL n'est pas très important, et il vaut mieux prévoir dès maintenant cette traduction dans l'écriture des gabarits et des vues.

**Comment by jmclem** [comment]
Perso, je me casserai pas les doigts là dessus, rares sont les personnes qui le lisent ou l'éditent directement. Je plaiderais pour 
/fr/user, /fr/songs, 
/en/user, /en/songs, 
/ru/user, ... (j'vais pas aller y mettre du cyrillique, quand même ;) )
/jp/user, ... (ni des sinogrammes)

**Comment by Luthaf** [comment]
Ok, partons là dessus =)

Est-ce que l'on prévoit malgré tout d'avoir un site multilingue ? Ça entraîne quelques différences au niveau de l'écriture des templates et des vues (utilisation de {% trans %} ou de _("blabla blabla") avec ugettext importé comme _)

**Comment by jmclem** [comment]
Oui ! C'est trop galère à rattrapper une fois le site 'fini'

**Comment by Luthaf** [comment]
Ok, je m'en chargerai après avoir fini la partie sur les utilisateurs (il manque l'inscription)

**Comment by oliverpool** [comment]
Si je comprends bien tout le texte (celui qui sera affiché à l'utilisateur) doit être rédigé en francais 
Si oui, alors il faut changer 
generator/models.py:95

```
 return _("Songbook {0}, used by {1}").format(self.songbook,self.user) 
```

**Comment by Luthaf** [comment]
Arf, oui en effet. Il m'a échappé celui là =)
