### ISSUE TITLE
Create fixtures to fill dB with some default values

### ISSUE THREAD

**Issue by jmclem** [patacrep/patanet#10]
fixtures should contain (more to come):
- information about test song files(artists, songs)
- user accounts
- some songbooks

**Comment by Luthaf** [comment]
C'est facile à faire depuis la zone d’administration. Pour sauver et importer les fichiers correspondants : 

```
python manage.py dumpdata > initial_data.json --> création de la fixture
python manage.py flush --> vide la BDD
python manage.py loaddata initial_data --> import de la fixture
```

Avec sqllite on peut aussi utiliser

```
python manage.py dumpdata > initial_data.json
rm db.sqlite3
python manage.py syncdb --> L'import est automatique dans ce cas.
```

**Comment by Luthaf** [comment]
J'ai modifié les champs 'slug' de la fixture. Pour mettre à jour sans tout supprimer : 

```
./manage.py flush --> vide la base
./manage.py loaddata generator/fixture/few_songs.json 
```
