### ISSUE TITLE
Propagate error messages

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#104]
J'ai eu du mal à debugger récemment parce que les messages d'erreur étaient trop lacunaires: `Failed Task 17 (state: ERROR)` par exemple.

Du coup j'ai propose des modif pour que les textes de certaines erreur "parentes" soient propagées

**Comment by oliverpool** [comment]
Avec ça j'ai eu un message:
`Error while pdfLaTeX compilation of "6-xxxx.tex" (see 6-xxx.log for more information).`

(Ce qui m'a permis de voir qu'il me manquait un paquet latex)

**Comment by oliverpool** [comment]
Est-ce que vous pensez que c'est pertinent de le fusionner ?
(ou on supprime cette branche - sachant que j'en ai plus besoin : j'ai fini de débugger mon installation)

**Comment by Luthaf** [comment]
On peut toujours la fusionner, mais il y a des logs de mis en place sur le serveur normalement. Ça reste un outil utile pour le dev.

**Comment by oliverpool** [comment]
A été fusionné (75d69a0)
