### ISSUE TITLE
Decide a scheme for db migration

### ISSUE THREAD

**Issue by jmclem** [patacrep/patanet#11]
from what I saw, django 1.6 doesn't handle db migrations (further Dev version does), so we are on or own to find a way to migrate existing dbs to newer or older versions.

**Comment by oliverpool** [comment]
The only real issue is the user db 
(because the song & artist dbs should be repopulated based on the content of the "songs" folder)

**Comment by jmclem** [comment]
I meant this issue to find a scheme; it will then be applied to whichever db objects that need it.

**Comment by Luthaf** [comment]
I do not understand. What' the point with db migration ? 

In the worst case, we can alter the table with PHPMyAdmin for example, or in command line with SQL directly.

**Comment by jmclem** [comment]
Je passe au français, on se comprendra mieux ;-)

La migration de bdd est un aspect important de la maintenance; oui, il est possible de tout faire manuellement, mais le risque d'oubli d'une table, d'un attribut est trop fréquent.

L'idée de la migration est que chaque commit qui contient une modification du schéma contiennent aussi les directives permettant d'une part la mise à jour automatique de la base de données (upgrade) et d'autre part son inverse (downgrade).

Ainsi, lorsque je veux déployer les 50 commits faits par 40 développeurs différents et impliquant 21 modifications de schéma (bon, ok, on n'en est pas là ;) ), j'ai une procédure de mise à jour automatisée et bien mieux garantie que manuellement.

C'est aussi sympa pour les autres devs qui, quand ils importent les changements des autres, n'ont pas à se poser de question  sur la mise à jour de leur bdd de dev.

C'est pourquoi c'est une partie intégrale des framework web "modernes" (RoR, Laravel, ...) prennent en charge la création de cette migration à partir des modifications de modèles. Django le supportera dans une prochaine version (https://docs.djangoproject.com/en/dev/topics/migrations/). En attendant, faut trouver qqc.

**Comment by Luthaf** [comment]
La version 1.7 avec gestion de ces migrations est prévue pour le 15 mai (version stable) et les dev gèlent l'ajout de fonctionnalités après-demain : 
https://code.djangoproject.com/wiki/Version1.7Roadmap
Donc on peut aussi décider d'utiliser la version de développement de Django, et de ne déployer la version stable du site qu'après le 15 mai (on peut toujours en déployer une version beta avant).

**Comment by oliverpool** [comment]
Je pense qu'il est vraiment important d'avoir un tel système lorsque le schéma de la bdd est amené à changer frequemment.
Or sur notre projet, la bdd est vraiment réduite (3 tables...)

Sinon on peut faire deux scripts d'install.
Un initial qui :
- efface toute BDD existante
- demande des identifiants admin
- créé les schémas de bdd nécessaires
- ajoutes les identifiants admin à la table user
- appelle le script suivant

Un juste pour les chansons
- supprime les tables artists et titles
- mets en place leur schéma
- parcours le dossier des chansons pour remplir les tables 

Sachant que le schéma de la table 'user' à très peu de chance d'être changée, il suffira de lancer le deuxième script après une mise à jour

**Comment by Luthaf** [comment]
Je ne vois pas pour à qui ces scripts serviraient ? À nous ? À d'autres personnes voulant déployer le projet ?

Dans le cas 1, la solution : script de mise à jour de la base de donnée depuis le dossier des chansons + Django1.7 est suffisant. On utilise alors 

```
python manage.py makemigrations --> Créé le fichier de migration (extension .py)
python manage.py migrate --> modifie la BDD
```

Dans le cas 2, Django apporte tous les outils d'installation : 

```
python manage.py syncdb --> créer les tables depuis les réglages de SGBDR du fichier <Project>/settings.py
```

De plus, un script perso ne permettrais pas de gérer tous les cas de SGBDR existants.

**Comment by jmclem** [comment]
Ok, l'idée est pas mauvaise, pas sans risque non plus. J'ai lu ici : http://www.jeffknupp.com/blog/2013/12/18/starting-a-django-16-project-the-right-way/ qu'il existe un package south compatible avec 1.6 et qui prend en charge les migrations : http://south.readthedocs.org/en/latest/index.html

Qu'en dites vous ? (je teste en attendant vos avis)

**Comment by Luthaf** [comment]
Je crois que les différences Django 1.6/1.7 se font justement sur ce problème de migrations des bases de données et sur des champs supplémentaires (composite fields) dans les formulaires. Pour moi, on devrait utiliser les versions stable certes, mais les plus récentes possibles. À savoir Python 3.3 et Django 1.7. Ainsi, on utilise les mêmes versions que l'on pourra utiliser dans 3 ans si on a besoin de modifier le code.

**Comment by jmclem** [comment]
Toutefois, django 1.7 est encore en alpha. Si South fait son job (et ça a l'air), je ne vois pas pourquoi prendre le risque de buter sur des pbs d'un package en cours de dev et à la release incertaine...

**Comment by Luthaf** [comment]
C'est vrai aussi =) On pourra faire le port vers les versions suivantes ultérieurement.

**Comment by jmclem** [comment]
Ok, I just committed the changes for using 'south'.

I encourage everyone to have a look at http://south.readthedocs.org/en/latest/tutorial/part1.html#changing-the-model

In short: 
- If you modify the model, you should call 

```
./manage.py schemamigration generator --auto
./manage.py migrate generator
```
- if you pull changes with a modified model, you should call

```
./manage.py migrate generator
```
- if you just install the whole thing, db config should go like :  

```
./manage.py syncdb
./manage.py migrate generator
```

**Comment by oliverpool** [comment]
Ca pourrait donc devenir une bonne idée d'inclure toutes ces choses dans un fichier INSTALL.md

**Comment by Luthaf** [comment]
Yep. Après je suis aussi pour avoir un ensemble de migrations de maintenant à la release, puis de supprimer les migrations de développement et de recommencer le cycle de migrations depuis cette release. Qu'en pensez-vous ?

**Comment by jmclem** [comment]
J'ai écrit dans le README.md quelques trucs sur l'installation, pas de pb pour les transvaser dans un fichier dédié.

D'accord pour remettre les migrations à zéro à partir de la release ou d'un feature freeze quelconque.

**Comment by oliverpool** [comment]
Ca me convient aussi
