### ISSUE TITLE
Idée concernant la légalité

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#115]
_(nouvelle idée qui relance l'issue #16)_

J'ai eu une idée pour éviter que le site web soit illégal:
**rendre le catalogue musical privé (par utilisateur)**

Dans l'idée, le site web agit comme un hébergeur de fichiers (exclusivement musicaux : chordpro), et c'est l'utilisateur qui doit importer son catalogue (fichier *.patasongs.zip par exemple) sur le site web. Une fois ces données fournies par l'utilisateur, le site patanet est capable de générer des carnets de chants à partir d'une sélection de ce catalogue utilisateur.

Le site ne fournir alors plus de contenu directement : il ne fait que mettre en forme des fichiers téléversés par les utilisateurs !

---

Au niveau technique, il faut donc rajouter des fonctions d'import / d'export de catalogue.
Concernant l'import, on peut simplement importer tous les chants dans une base commune (en évitant les doublons : si une autre personne l'a téléversé, on rajoute une entrée dans la table pivot) et rajouter une table pivot listant les chants que l'utilisateur a téléversés.

Dans un premier temps (dans la phase béta), on peut "importer" automatiquement le catalogue courant lors de la création du compte. Lorsque le site devient très populaire, on bascule en import manuel pour éviter d'être attaqué par les ayants droits.

---

**En résumé** : c'est une idée qui n'est pas forcément très simple au niveau technique ou très ergonomique (lors de la création de compte, il faut importer un ficiher chansons.patasongs.zip), mais qui devrait éviter des ennuis légaux.

**Comment by Soundy25** [comment]
<< Le site ne fournir alors plus de contenu directement : il ne fait que mettre en forme des fichiers téléversés par les utilisateurs ! >> (Comment on fait des "reprises de posts" dans un new msg ici ?)
Ah là, ça m'a l'air plus légal effectivement, les users sont responsables de leurs imports et l'hebergeur fourni un service de rendu.

j'ai parcouru le post de Luthaf hier soir, mais prendre le temps de relire tout ça précisément.
Je ne sais pas si des Tabs sont considérées au même titre que la partition ou que les textes soumis au droit d'auteur, c'est à creuser également.

**Comment by Soundy25** [comment]
http://www.juristudiant.com/forum/tablatures-de-guitares-sur-internet-droits-d-auteurs-t3196.html

<< Autrement dit, si je réalise une tablature d'un morceau c'est comme si je prenais un livre récemment écrit et que je commentais certains passages.

Commenter un livre, reprendre certains passages ne porte pas atteinte au droit d'auteur si je cherche à expliquer le but de l'auteur, si je le fais dans un but pédagogique, que mes citations du livre sont faites pour étayer mes propos, etc.

Une tablature répond à ce schéma : tu ne distribues pas le morceau de l'auteur dans sa totalité : concrètement, tu ne reproduis qu'une partie du morceau (en général, un instrument), partie que tu as toi-même interprétée et qui peut différer du morceau original (ex. : tab transcrite en DO alors que le morceau original est en FA). >>

**Comment by Luthaf** [comment]
Alors je ne suis pas forcément pour l'utilisation de base de donnée privée, mon idée était plus de partager le contenu et de permettre aux gens d'avoir accès à des chansons **facilement**, même sans être musicien. Le public initial de ce site reste des chefs scouts qui cherchent à faire un carnet pour leur troupe. Après si ça peu aussi servir à d'autre tant mieux, mais le plus simple est l'utilisation du site, le mieux c'est.

Ensuite, concernant le _Lorsque le site devient très populaire_, je ne pense pas que le but est que ce site devienne très populaire. S'il devient assez populaire pour que les ayant droits en soit gênés, il devra alors être possible de rémunérer ces ayant droits d'une manière ou d'une autre, l'audience du site étant suffisante.

Enfin, l'ensemble de la base de chansons est disponible en ligne depuis les débuts de patacrep, maintenant dans le dépôt de patadata, et personne n'en a jamais été gêné.

Ma position reste sur cette solution (dans l'issue originale) : 

> nous l'installons quelque part de manière "marginale", le service est connu de et utilisé par quelques troupes par ici et par là, le serveur coûte pas trop cher parce que la charge est légère, et la CSDEM ne s'en formalise pas je pense => OK pour nous

**Comment by Soundy25** [comment]
Ok, en plaçant qq balises <meta name="robots" content="noindex". dans les sources ET en rendant l'accès sécurisé via login+mdp, on réussira à rester discrets...

**Comment by oliverpool** [comment]
Ok, du coup on garde cette idée sous le coude seulement en cas de popularité incontrôlée ;-)
