### ISSUE TITLE
Change pagination of artists and songs

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#117]
Sachant que l'alphabet est (quasi ?) complet pour les artistes et les chansons, je propose de changer le fonctionnement de la pagination pour avoir une page pour chaque lettre (+1 pour les chiffres, +1 pour les caractères spéciaux).
`?page=a`,...,`?page=z`,`?page=0`,`?page=-`

Cela permettra notamment de faire qu'un clic sur "retour à la liste des artistes" renvoie sur la bonne lettre directement.
(on peut aussi imagnier une page d'accueil des artistes/chants qui liste les lettres de l'alphabet)

---

On pourrait carrément changer les urls : 
`artists`
`artists/a/`... 
`artists/a/aaron` (pour éviter les conflits avec des potentiels artistes à une lettre)
et de même pour les chants

_mais du coup ça devient pénible pour les templates, dans les routes... il y a moyen de générer cela automatiquement peut être ?_
_à moins de gérer cela en modifiant le template tag url, cf http://stackoverflow.com/a/20009830/3207406_

**Comment by Luthaf** [comment]
> mais du coup ça devient pénible pour les templates, dans les routes... il y a moyen de générer cela automatiquement peut être ?

Dans ce cas, on peut simplement virer la pagination et ajouter une `ListView` pour les URL de la forme `/artists/<letter>/`, et ajouter un micro check dans la `DetailView` correspondant à un artiste pour que une URL `/artists/f/aaron` revoie une 404.
