### ISSUE TITLE
Improve "Download Songbook" page

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#128]
Je compte m'attaquer bientôt à la page "Téléchargement" des chants.

Actuellement elle ressemble à cela:
![tele](https://cloud.githubusercontent.com/assets/3864879/6788784/436dc1a2-d19c-11e4-8460-3aeadd399202.png)

J'ai dans l'idée de faire quelque chose proche de la liste des carnets:
![carnets](https://cloud.githubusercontent.com/assets/3864879/6788798/50979aba-d19c-11e4-9fc0-41f3b572707b.png)

Chaque ligne (correspondant à une mise en page), indiquera à l'aide de pictogrammes:
- l'orientation (portait/paysage)
- la taille (A4... lorsque cela sera implémenté dans patacrep)
- la présence des accords
- l'état du téléchargement (disponible, en cours de compilation, erreur de compilation, pas à jour)

Un clic permettra d'afficher plus, notamment si les diagramme d'accord sont rappelés en début de chant, les couvertures d'album etc.

Concernant les nouvelles mises en pages, plutôt que de mettre le formulaire directement sur la même page, je pense créer une page séparée (exactement comme "Nouveau Carnet").

Qu'en pensez-vous ?

**Comment by Soundy25** [comment]
> je pense créer une page séparée (exactement comme "Nouveau Carnet")

Oui, j'aime bien l'idée de proposer les mêmes types d'actions de façon identiques, ça permet une meileure appropriation de l'outil par l'utilisateur.

> Je pense aussi qu'il serait bien que la création d'un carnet entraîne automatiquement la création d'une mise en page par défaut (A4, portrait, avec les accords).

Je ne suis pas sûr d'avoir tout saisi. 
J'ai compris que lors de la création d'un nouveau carnet, tu proposes que le système lui applique une mise en page par défaut (A4, portrait, avec les accords), libre à l'auteur du carnet de la modifier après coup, juste avant de généré le nouveau carnet. S'il choisi de modifier la mise en page, cela entraine l'association de la mise en page choisie avec le compte de l'auteur (table de relation). Grace à ces relations (exposées dans la Liste des mise en page disponibles, soit l'équivalent d'un onglet "Mes mises en pages"), il pourra éditer ses carnets selon les mises en page qu'il a déjà utilisé auparavant. C'est ça ?
Si c'est ça, je trouve ça bien.

**Comment by oliverpool** [comment]
Actuellement les relations sont ainsi:

```
[User] -- has_many --> [Songbook] -- has_many --> [Task] -- has_many --> [Layout]
```

_Task est une classe "technique" utilisée pour gérer la génération du carnet de chant_

Un utilisateur créé (manuellement) un carnet de chant, puis créé (manuellement) un Layout, qui créé (automatiquement) une Task.

J'aime bien ton idée d'associer des Layout à un utilisateur (et non à un carnet comme actuellement), cela permet d'utiliser la même mise en page personnalisée pour plusieurs carnets !

Et je maintiens mon idée de créé automatiquement une mise en page (par défaut) pour tous les utilisateurs.

@Luthaf :
Du coup un simple changement
`Songbook <-> Task <-> Layout` en `Songbook <-> Task <-> Layout <-> User` me parait pas mal.
Avec création automatique de Layout par défaut lors de la création de l'utilisateur.

**Comment by Luthaf** [comment]
Alors, la relation `Task <-> Layout` n'est qu'une relation d'observation, de même que la relation `Task<->Songbook`. Une tache, c'est compiler un carnet (contenu) donné selon une mise en page (Layout) donnée.

Si je me souviens bien, les Layout ne sont pas associées à un utilisateur pour que les mises en page puissent être partagées de manière globale au niveau du site, et donc reprises par plusieurs utilisateurs. Et elles ne sont pas associées à un carnet pour pouvoir être reprises par différents carnets en effet, même si rien n'a été mis en place.

Mais ça me semble être assez peu utile en fait, donc on pourrait tout à fait associer les mises en page à un utilisateur particulier. 

Concernant les valeurs par défaut, on pourrait juste préciser des valeurs par défaut pour les attributs de `Layout` en fait.

**Comment by oliverpool** [comment]
Ok.

Je m'y mets dans quelques jours et je vous tiens au courant.
Si vous avez d'autres idées, n'hésitez pas !

**Comment by Luthaf** [comment]
Tu as besoin d'un coup de main pour le back ? Je n'ai pas des masses de temps à passer, mais je peut faire quelques bouts.

**Comment by oliverpool** [comment]
Ca devrait le faire: je commence a comprendre comment ca fonctionne.
J'apprecie que tu jettes un coup d'oeil au code (et si je suis perdu, je t'appelerai a l'aide ;-)

**Comment by Luthaf** [comment]
> J'apprecie que tu jettes un coup d'oeil au code

Ça toujours =)

**Comment by oliverpool** [comment]
(il est préférable de poursuivre la discussion sur la PR #129)
