### ISSUE TITLE
Choix d'un design

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#13]
Comme vous avez pu le remarqué, j'ai commencé à faire un petit CSS pour le site. Je trouve ça plus simple pour organiser les templates HTML en même temps.

Du coup, je partait sur un design semblable au site de Patacrep!, avec un fond clair et des nuances de verts/jaunes (http://colorschemedesigner.com/#1T51T8UrXOcg0). Qu'en pensez-vous ?

**Comment by oliverpool** [comment]
Je suis bien incapable de proposer des couleurs (donc ta proposition me convient ;-)

Je suis en train de réfléchir au design global (disposition / layout) et je suis assez favorable à ressembler à wikipédia : 
- cela permet de souligner l'aspect communautaire de la rédaction des chants
- l'agencement global est assez pertinent

Dans un aspect plus général, est-ce qu'on utilise un framework css (type bootstrap que je commence à connaitre un peu) ou est-ce qu'on fait quelque chose depuis zéro ?

**Comment by Luthaf** [comment]
Mouais, je ne suis pas fan du style wikipedia. On peut juste garder le layout général =)

Pour la manière de coder, je ne sais pas. Boostrap exige de l'HTML spécifique, non ? Moi je partait sur quelque chose à la main.

**Comment by oliverpool** [comment]
Concernant wikipédia, je pensais juste au layout :

```
                                                                            Create Account | Login
                                                           Admin  | Profile | My Songbooks | Logout

  SUPER LOGO
                 +------+------+--------------+----------------------------------------------------+
                 | Read | Edit | View history |                                     |   Search     |
                 |      +------+--------------+----------------------------------------------------+
> Home           |
                 |
> Artist list    |
                 |
> Songbooks      |
                 |
> Contribute     |
  - First steps  |
  - Help         |
  - Last updates |
  - Dev          |
                 |
> Links          |
  - Patacrep     |
  - Github       |
                 |
> Language       |
   - Francais    |
   - English     |
                 |
> Contact        |
                 |
                 +
```

**Comment by oliverpool** [comment]
Pour bootstrap, je l'utilise actuellement, et je fais tout pour éviter qu'il ne s'insère dans l'HTML (j'ai créé des 'mixins' pour les appliquer à mes classes).
Les deux choses qui sont vraiment intéressantes (de mon point de vue) : les formulaires et la grille responsive.

Edit : mais c'est vrai que c'est une artillerie un peu lourde pour notre modeste projet

**Comment by Luthaf** [comment]
Sinon, je commençait à jeter un œil sur le langage LESS (utilisé par Bootstrap). Ça a l'air pas mal, et il y a un support Django pour la partie dev :  (compilation des fichiers .less à la volée). Puis quand on est fixé on peut figer le fichier en un .css.
Le lien pour l'utilisation avec Django : http://stackoverflow.com/a/8726853

**Comment by oliverpool** [comment]
J'utilise en effet LESS pour modifier lourdement bootstrap.
C'est effectivement très pratique ! (notamment pour changer les couleurs en un clin d'oeil)

Edit : la méthode proposée par le lien est un peu lourde, elle requiert notamment l'installation de Node.js... 
Pour la dev, (comme suggéré par http://www.caktusgroup.com/blog/2012/03/05/using-less-django/) il me parait plus aisé d'incorporé le fichier less et de le compiler côté client via un script JS. Une fois le design definitif atteint, un de nous le compile en css (j'ai déjà des outils installés à cet effet)

**Comment by Luthaf** [comment]
On part là dessus du coup ? Design à la main avec LESS et compilation coté client pour la dev, puis compilation finale à la release ?

Pour le layout, je me demande surtout si un type Wikipedia passera bien ou non avec l'affichage de chants : le nombre de colonnes d'un chant est fixe, donc ça peut être étrange sur des hautes résolutions.

**Comment by oliverpool** [comment]
Je pense que c'est moins pertinent de faire plusieurs colonnes sur un affichage numérique : 
par exemple je ne connais aucun journal en ligne qui fasse plusieurs colonnes ! 
(pour les pdf c'est une autre histoire)

Edit: et ok pour le design from sctrach en less avec compile cote client pdt la dev

**Comment by Luthaf** [comment]
Non, je parlait du nombre de colonnes de texte : on a pas plus de 80-100 caractères par ligne, donc ça va faire un peu vide sur une grande largeur. Mais il faut tester pour voir ce que ça rend.

**Comment by oliverpool** [comment]
Ok, je vais essayer de faire quelques tests de design

**Comment by oliverpool** [comment]
Voilà un design inspiré (plagié ??) de wikipédia :
http://jsbin.com/OpuJEWuS/1

(je suis en train d'écrire un script JS pour mettre en forme le latex d'un chant, c'est donc la seule chose à ne pas regarder ;-), je l'ai mis pour avoir un apercu avec du texte)

edit : si l'agencement global vous convient, je coderai les templates (agencement global : est-ce que les regroupements de liens sont cohérent selon vous - tous le design reste modifiable en less/css)

**Comment by Luthaf** [comment]
C'est cool ! 

Voici des remarques en vrac : 
- J'ajouterai bien une balise <aside> pour récapituler les infos des chants (auteur, titre, utilisé dans n carnets de chants, capo, tonalité, un lien pour transposer via JS, ...) et avoir un menu déroulant "ajouter à : moncarnetdechant1, moncarnetdechant2, moncarnetdechant3 ; créer un nouveau carnet ..." 
  Comme Wikipedia en fait ^^
- Et paradoxalement, je trouve que ça ressemble encore un peu trop à Wikipedia... Mais ça doit pouvoir se régler à coups de CSS =) Sinon, le code HTML du jsbin n'est là que pour l'exemple ? Je le trouve assez indigeste ... =)
- Sinon, je trouve qu'il y a un grand blanc entre le texte de la chanson et le bord droit de la page.
- Il manque un lien vers 'mes recueils' (au passage, on parle de recueils ou de carnets de chants ?)

Deux questions sur les liens qu'il y a sur la page : le lien 'desireless' conduit vers une liste des chansons de cet album ? Parce que pour l'instant il n'y a pas de gestion des albums. Et 'index des chansons' conduit vers une liste de toutes les chansons ? Auquel cas il faut ajouter cette vue.

**Comment by oliverpool** [comment]
Merci pour les remarques !

La source est là : http://jsbin.com/OpuJEWuS/1/edit (le code HTML n'est pas si indigeste : j'ai fait au mieux pour l'indentation)
- Les infos des chants (capo & co), est ce qu'on fait comme wikipédia ? un bloc aligné à droite avec tout (au même endroit que l'album)
- le menu déroulant d'ajout à un recueil: je le verrai bien en haut, à côté de "Historique" par exemple (action chanson)
- Tout peux se régler à coup de CSS, sauf les regroupements des liens (càd que "Lire", "modifier" et "historique" seront dans tous les cas ensembles
- Le liens "mes recueils" aurait sa place dans la barre supérieure "utilisateur connecté"
- ca pourrait être pas mal effectivement qu'un clic sur l'album conduise à l'album correspondant (mais on peut zapper cette fonctionnalité - au moins dans un premier temps)
- de même, les liens de la colonne de gauche peuvent tout à fait être modifiés

=> Le but principal du design est de se mettre d'accord sur l'agencement global et quels sont les menus à faire. Ici j'ai fait
- un menu de navigation globale (à gauche)
- un menu utilisateur (tout en haut)
- un menu chanson (en haut)
- un menu de recherche (en haut à droite)

Est-ce que ces menus conviennent? est-ce qu'il faut en supprimer ? en ajouter ? en fusionner ?
Le contenu exact ainsi que la disposition peuvent être décidés bien plus tard sans soucis!

**Comment by Luthaf** [comment]
Ok. Pour le code HTML, je suis un peu tatillon, mais je ne vois pas l'intérêt d'une div global-container quand on a un body. Sinon en fait oui, le reste n'est pas trop moche =). J'ai été rebuté par la quantité de scripts en fait.
- Pour les infos, oui partons comme Wikipedia. On verra après si il faut modifier tout ça
- Ok pour le menu déroulant

Sinon le layout global me va =) Quand tu parles de coder les templates, ce sont des templates Django ou des templates HTML plus génériques ?

Edit -- Sinon, j'ai jeté un œil de plus près au CSS actuel. Si tu comptes utiliser le même, je suis pour mettre toute la partie 'hacks' initiale dans un fichier séparé.

**Comment by oliverpool** [comment]
global-container ne sert à rien (il peut effectivement être remplacer par body)
Je parle de templates Django
Le CSS est en fait un ensemble de LESS compilés ;-)

**Comment by jmclem** [comment]
J'aime bien l'ensemble. Une remarque toutefois, peut-être hors propos s'il ne s'agit dans cette issue que de l'aspect (charte) graphique général : il me manque un accès ultra visible à la fonction principale : "créer votre recueil". Je pense que c'est ce que 90% des utilisateurs vont faire, sans vouloir se lancer dans l'édition de chants ni dans tous les liens, contribution, ....
J'aurais vu un truc du genre (un peu simplifié peut-être ;) ):
- gros lien bien visible "créer votre recueil" (suivi de identification si nécessaire)
- choix des chants dans une liste (avec recherche dynamique)
- choix des options
- générer
  La page telle qu'elle est aujourd'hui : 
  ![screenshot from 2014-01-22 09 28 33](https://f.cloud.github.com/assets/721746/1972026/53077614-833f-11e3-95d2-8ffe5bbcfd88.png) me semblerait tout à fait adaptée pour un utilisateur qui se déclare "avancé".

Bon, j'l'ai déjà dit, le design graphique, c'est pas mon truc, donc je me lance pas trop dans les contribs là dessus, je vous suis reconnaissant que vous le fassiez !

**Comment by Luthaf** [comment]
Oui, en effet. Mais ce n'est pas la page d'acceuil, plutôt une page pour montrer les chants. Il faut voir comment cette dernière se présentera =)

**Comment by oliverpool** [comment]
La page que je présente est pour les "visiteurs simples" (ie non connectés)
Pour évaluer la puissance nécéssaire au serveur pour compiler les carnets de chants, je pense qu'il faut d'abords limiter la compilation aux utilisateurs connectés.

Comme le fait remarquer Luthaf, quand tu créé ton recueil, tu ne vas pas aller sur la page d'un chant: tu vas plutôt parcourir les titres/artistes et c'est là qu'il faudrait ajouter les boutons adéquates ! (sur la page d'un chant, ca peut être plus discret, à côté de historique par exemple)

**Comment by oliverpool** [comment]
Après avec un CSS un peu adapté, quand tu clic "imprimer" dans ton navigateur, ça peut te faire déjà des pages sympas pour travailler des chants en solo (sans faire de carnet de chants construits) [ca fait une fonction secondaire au site: télécharger en pdf des chants individuels]

**Comment by Luthaf** [comment]
Je suis d'accord pour limiter dans un premier temps la compilation aux utilisateurs connectés, mais il faudrait à terme que tout le monde puisse tester le site sans s'inscrire.

Pour l'impression en pdf, il faudrait un autre CSS qui supprime les menus, en-tête, etc.

**Comment by Luthaf** [comment]
Sinon, il faudra aussi voir pour rendre le design adaptatif comment on modifie l'agencement de la page. Je vais réfléchir un peu là-dessus, mais j'ai déjà quelques idées.

**Comment by oliverpool** [comment]
pour l'impression pdf il suffit d'utiliser  @media print{} avec les styles correspondants (ca peut effectivement se faire dans une autre feuille de style)
Le design actuel est adaptatif (ie il est "élastique"), est-ce qu'il est vraiement pertinent de le rendre "responsive" ? 
Je pense que le design que je propose est opérationnel sur tablette : il reste la question des smartphones, mais ce n'est clairement pas le type d'usage initalement prévu...

**Comment by Luthaf** [comment]
Je ne sais pas, mais au moins il faut se poser la question =)

Ça peut être utile quoiqu'un peu gadget d'accéder au site depuis le smartphone, par exemple pour ajouter à un carnet une super chanson que l'on entend un soir à la veillée.

**Comment by oliverpool** [comment]
certes, mais ca reste une utilisation marginale ;-) (si le site est "utilisable" sans être spécifiquement adapté aux smartphones, dans un premier temps, c'est acceptable)

**Comment by Luthaf** [comment]
Bon, tu t'affecte à cette issue du coup oliverpool ? =)

**Comment by Luthaf** [comment]
La discussion continue ailleurs #23 !
