### ISSUE TITLE
Add default layout when installing

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#131]
Des mises en page par défaut sous forme de `fixtures` django vaudrait le coup, cf https://github.com/patacrep/patanet/commit/ce5b01021559febec99b9f05af0398b7c436793a#commitcomment-10725304

**Comment by oliverpool** [comment]
+1

**Comment by oliverpool** [comment]
Attention: cela n'est plus ajouté automatiquement depuis Django 1.7 (https://docs.djangoproject.com/en/1.8/howto/initial-data/#automatically-loading-initial-data-fixtures).

Il vaut mieux le mettre directement dans la migration : https://docs.djangoproject.com/en/1.8/topics/migrations/#data-migrations

**Comment by oliverpool** [comment]
A moitié fait dans 154f97673 (des `papersizes` sont ajoutés par défaut, mais pas de layout)

**Comment by oliverpool** [comment]
Je pense que les fixtures de `papersizes` sont suffisantes (et je n'ai aucune idée de comment choisir quels paramètres à choisir pour les mises en page par défaut)
