### ISSUE TITLE
Affichage des chants

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#15]
J'ai commencé à écrire en JS un script pour mettre en forme le contenu LaTeX des chansons (un peu de travail en moins pour le serveur ;-)
Un aperçu de quelques chants est dispo ici : http://jsbin.com/OpuJEWuS/1

Dites-moi ce que vous en pensez, est-ce que vous voyez des bugs des incohérences ?

PS : si vous désactivez JS vous verrez le contenu original (ou sur la source : http://jsbin.com/OpuJEWuS/1/edit)

**Comment by Luthaf** [comment]
Ça rend plutôt bien =)

Je pense que dans un premier temps, il faut ignorer les commandes du type \lilypond, \gtab, etc. Pour les afficher, il faudra ajouter de l'ajax je pense (Si JS trouve une commande \lilypond, il va chercher le fichier .ly correspondant puis le transforme en partition). La transposition n'a pas l'air de fonctionner non plus =)

Après je me pose une question sur le parsing : c'est cool, ça permet de faire des prévisualisations lors de l'édition en temps réel, des transpositions, mais ça pose un problème pour moi de référencement : je ne pense pas que une ligne comme `\[G]Welcome to the Hotel Cali\[D]fornia` soit équivalente à `Welcome to the Hotel California` pour nos amis les moteurs de recherche.

**Comment by jmclem** [comment]
Oui, ça rend bien, chapeau ! 

Je partage les réserves de Luthaf sur l'utilisation systématique côté client pour l'affichage des chants - mais pourquoi pas appeler ta fonction js lors de l'import bdd pour cacher le résultat HTML direct ? Comme ça, le serveur fournirait du code HTML, récupéré en bdd, préformatté de la chanson avec accords. Et bien sûr, pour la prévis lors de l'édition, c'est super :)

**Comment by Luthaf** [comment]
Quitte à mettre en cache, autant parser avec python, non ? Je ne sais pas quel langage est le plus rapide, mais on peut écrire la fonction directement dans Django, qui de toute manière doit ouvrir le fichier .sb pour le servir. Il ne faut pas ajouter des trucs pour utiliser JS coté serveur ?

**Comment by jmclem** [comment]
C'est vrai, mais je vois de gros avantage dans le fait d'avoir une seule et même fonction utilisée partout:
- le résultat est toujours le même
- la maintenance est simplifiée

Comme il s'agit du cache, à l'import, la vitesse importe peu. Avec node, rhino, v8, ... tu peux interpréter du JS en ligne de commande.

**Comment by oliverpool** [comment]
merci pour les commentaires (et les compliments ;-)
- concernant les commandes "spéciales" (lilypond & co), je les affiche en "texte brut" et en léger transparent pour signifier à l'utilisateur qu'elles sont bien là, mais non supportées dans l'affichage HTML (au moins pour le moment). Si je les cache totalement, l'utilisateur peut se demander où sont passées ses modifs (mais je peux accentuer leur transparence)
- la transposition à pas l'air de fonctionner => effectivement, je ne transpose pas les accords...mais j'afffiche quand même qu'il faut les transposer ;-)
- pour les moteurs de recherche c'est effectivement un problème (mais il vaut mieux être référencé via les termes "recueil de chant" que les paroles d'une chanson...sinon on peut toujours envoyer des pages différentes quand on détecte un moteur de recherche - sans les accords)
- "appeler la fonction js lors de l'import" comme le signale luthaf cela impose d'installer node.js sur le serveur...(ou alors des outils apparement plus très développés : http://andrewwilkinson.wordpress.com/2012/01/23/integrating-python-and-javascript-with-pyv8/)
- concernant le cache, je pense que c'est une très mauvaise idée de le stocker dans la bdd (un fichier simple est beaucoup plus pertinent)

Du coup vous m'avez donné une idée:
- on créé un cache des chansons (un fichier .sg = un fichier de cache sg.html par exemple) avec une fonction python qui supprime tous les accords et parse les blocks (verse, verse*, bridge, choruse)
- on affiche ce texte sur la page
- via ajax, on appelle le fichier .sg et on le parse avec ma fonction

=> c'est compatible avec les moteurs de recherche
=> la fonction de parsing de python n'est pas très complexe (quelques regex bien placées) et n'a pas besoin d'évoluer avec le temps
=> l'utilisateur voit immédiatement la chanson (sans les accords), puis les accords sont chargés et parsés
=> pour la recherche, il suffit de faire un grep sur le dossier qui contient le cache (je maintien que les fichier .sg n'ont RIEN à faire dans la bdd) [on pourrait limiter la recherche sur les paroles aux utilisateurs connectés - ou alors la confier à google puisque nos pages sont facilement lisibles ;-]

**Comment by Luthaf** [comment]
Concernant le cache, il n'y a aucun besoin de le mettre dans la BDD =) Django permet d'utilise plusieurs moteurs de cache, dont un dans la BDD, un dans la RAM, un sur le système de fichier et un avec MemCached (https://docs.djangoproject.com/fr/1.6/topics/cache/).

Pour la recherche, on peut encore utiliser les BDD, ce qui est mis en cache est une vue. Et il suffit d'écrire une règle de validation du cache qui prenne en compte la date de dernière modification. Ici, je pense que le cache sur le système de fichier est le plus adapté.

**Comment by jmclem** [comment]
c'est bon, c'est bon, arrêtez l'avalanche ;) on est d'accord, j'ai mis en bdd un peu rapidement, c'est plus la notion de cache qui m'était importante.

Je m'inquiète un peu - peut-être à tord - de la profusion d'interpréteurs : un JS, un python/RegExp, un python/plastex ... Il y a possiblement pas mal de travail derrière chacun d'entre eux.

**Comment by oliverpool** [comment]
je ne suis pas convaincu de l'interêt de plastex du coup: 2 suffisent largement (un python léger et un JS complet)

**Comment by Luthaf** [comment]
Ça dépend: a quoi sert PlasTeX ? Il faut que je vérifie, mais il est abondemment utilisé pour générer le .tex depuis le .sb et peut être pour les fichiers d'index. 

En soi, on peut s'en passer pour l'affichage des chants, mais pas trop pour la compilation. Du coup pourquoi ne pas s'en servir pour l'affichage aussi ?

**Comment by jmclem** [comment]
Plastex sert à parser LaTeX. C'est donc très complet. C'est donc utilisé par songbook qui doit tout analyser.

Pour nous, c'est un peu différent: 
- pour remplir notre cache/bdd, seuls quelques champs sont intéressants
- pour l'affichage, seule l'intérieur du song nous concerne.

Nous nous retrouvons donc à devoir analyser seulement un très petit sous ensemble de la syntaxe latex/song, ce qui explique la possibilité de le faire avec des moyens simples, comme les regexps.

-- edit
je n'ai pas encore de réponse à ce qui est judicieux; je pense qu'il faut essayer pour se décider.

**Comment by oliverpool** [comment]
A quoi sert PlasTex : http://www.patacrep.com/forum/viewtopic.php?pid=745#p745 Louis doit en savoir pas mal sur la question !

**Comment by Luthaf** [comment]
> A quoi sert PlasTex

C'était une question rhétorique ^^ En gros c'est un parseur TeX complet, avec gestion de sortie dans plusieurs formats. Je viens de me souvenir qu'il gère automatiquement une sortie HTML pour des documents LaTeX classiques. Je vais jeter un œil pour savoir si c'est facilement adaptable à notre problème !

Le lien pour le rendu d'un document TeX en (x)HTML : http://plastex.sourceforge.net/plastex/sect0020.html

**Comment by oliverpool** [comment]
(maintenant que j'ai un peu de temps, je vais chercher un exemple de code pour : parser un fichier tex et effectuer le rendu avec un template personnalisé)

**Comment by jmclem** [comment]
Je m'étonne d'une chose : pourquoi Tri\ Yann dans la fichier "la jument de Michao" n'a pas été traduit par PlasTeX? C'est précisément une des choses que j'aurais attendue de l'appel song/utils/parsetex/plastex. Ou ais-je mal compris le rôle de plastex?

**Comment by Luthaf** [comment]
Bonne question ... la fonction plastex est une surcouche du parseur [PlasTex](http://plastex.sourceforge.net/plastex/index.html), et je ne sais pas comment ce dernier gère les commandes d'espacement (`\`) LaTeX.

**Comment by paternal** [comment]
J'ai l'impression que le « Python léger » à coup d'expressions régulières pour l'analyse syntaxique va vite montrer ses limites : si je l'ai abandonné pour songbook-core, c'est parce que ça ne convenait vite plus. Notamment, vu les expressions régulières utilisées, on était très contraint sur les sauts de lignes (lesquels étaient autorisés ou interdits). J'ai l'impression que : 
- soit vous utilisez du Python léger à coup d'expressions régulières, auquel cas le code sera soit incompréhensible (expressions régulières longues comme mon bras) soit incomplet, voire les deux ;
- soit vous réutilisez le code PlasTeX déjà mis en place, qui fonctionne déjà, et ça me parait nettement plus simple. Sachant que je peux vous donner un coup de main pour vous expliquer comment ça marche.

---

> Bonne question ... la fonction plastex est une surcouche du parseur PlasTex, et je ne sais pas comment ce dernier gère les commandes d'espacement () LaTeX.

J'ai mon idée sur la question. Je répond ce soir quand je suis chez moi avec mes outils sous la main (je répond du boulot).

**Comment by paternal** [comment]
Désolé : je répond un peu plus tard qu'annoncé.

> Je m'étonne d'une chose : pourquoi Tri\ Yann dans la fichier "la jument de Michao" n'a pas été traduit par PasTeX? C'est précisément une des choses que j'aurais attendue de l'appel song/utils/parsetex/plastex. Ou ais-je mal compris le rôle de plastex?

En fait, je ne suis pas sûr de bien comprendre ta question : à quel moment reçois-tu la valeur "Tri\ Yann", et que comptes-tu en faire ? A priori, PlasTeX ne perd pas d'information, donc il n'y a pas de raisons pour supprimer cette espace. Maintenant, si pour l'afficher, tu veux la supprimer, ça doit être possible, au sein de plastex, ou avec un string.replace().

**Comment by Luthaf** [comment]
Dans le fichier "la_jument_de_michao.sg", l'artiste est noté `Tri\ Yann`. Le problème ici est que après utilisation de la fonction `parsetex`, on récupère comme nom d'auteur TriYann, sans espace. Tandis que dans d'autres fichier, "Tri Yann" donne bien Tri Yann.

**Comment by paternal** [comment]
Je confirme, mais je ne sais pas si c'est normal. Qu'est-ce que tu veux faire avec ça ? Récupérer le nom de l'auteur ?

**Comment by jmclem** [comment]
Oui, avec les caractères spéciaux convertis : Tri\ Yann -> Tri Yann.
Pourrait-il aussi y avoir des nom du style `St\'ephane`, bref, une notation spécifique à LaTeX, qui n'a pas à apparaître sur les pages web?
Quel utilitaire pourrait interpréter et convertir ça?

**Comment by paternal** [comment]
Même résultat avec `~` comme espace insécable. Par contre, les `è` et `\^e` sont correctement traités. Pour le moment, je n'arrive pas à voir si c'est un bug ou une fonctionnalité de plasTeX. Mais vu l'heure qu'il est, je n'en saurai pas plus ce soir.

**Comment by oliverpool** [comment]
> Même résultat avec `~` comme espace insécable.

Si je comprend bien https://github.com/patacrep/songbook-core/blob/master/tex/songs.sty#L3662
(sans garantie), c'est traité par le songbook package

**Comment by paternal** [comment]
Oui, mais indépendamment de ça, je pense que ça devrait être traité par plasTeX aussi.

J'ai corrigé ça : 3121c28c8f5727e67900c5ce0fb5bd43f79430ef (dans ma branche next-louis)

**Comment by Luthaf** [comment]
Du coup, pour l'affichage a l'utilisateur final, on utilise plasTex et une mise en cache ? 

Du coup il faudrait implémenter plasTex pour la 0.1 et la mise en cache pour plus tard ?

**Comment by paternal** [comment]
> Je m'étonne d'une chose : pourquoi Tri\ Yann dans la fichier "la jument de Michao" n'a pas été traduit par PlasTeX? C'est précisément une des choses que j'aurais attendue de l'appel song/utils/parsetex/plastex. Ou ais-je mal compris le rôle de plastex?

Pour info, en essayant de corriger ce bug (dans PlasTeX) je me suis rendu compte qu'il a déjà été corrigé ([ici](https://github.com/tiarno/plastex/commit/682a0d223b99d6b949bacf1c974d24dc9bb1d18e) et [ici](https://github.com/tiarno/plastex/commit/76bb78d5fbaac48e68025a3545286cc63cb4e7ad)). Il n'y a plus qu'à attendre que ça entre en production pour pouvoir supprimer [ma correction](https://github.com/patacrep/songbook-core/commit/3121c28c8f5727e67900c5ce0fb5bd43f79430ef). J'ai mis les références à ça [dans le code](https://github.com/patacrep/songbook-core/commit/b285650c52856cbedda56bb860646d15bfa5a107).

**Comment by Luthaf** [comment]
Alors j'ai commencé à regarder comment faire ça, et je me dis que le plus simple serait d'effectuer le parsing des sources avec plastex (classe `TeX`), puis de faire un pré-traitement du résultat et enfin d'effectuer le rendu avec le système de templates Django. 

Par contre, je ne vois pas dans la doc comment traiter les commandes spéciales du package songs. En effet, les commandes d'accords `\[G]` ne semblent pas être facilement lisibles par plasTeX. Ce dernier reconnais bien mieux les commandes du type `\macommande[optionnel]{obligatoire1}{obligatoire2}`. @paternal , comme tu connais un peu mieux que moi cet outil, tu aurai une idée de vers où chercher pour récupérer les valeurs des accords ?

**Comment by paternal** [comment]
> @paternal , comme tu connais un peu mieux que moi cet outil, tu aurai une idée de vers où chercher pour récupérer les valeurs des accords ? 

D'accord : c'est sur ma todo liste.

**Comment by Luthaf** [comment]
Comme discuté dans l'issue (#41), j'ai mis en place une solution **temporaire**, qui fonctionne mais qui ne reconnait pas toutes les commandes, ni toutes les configurations possibles pour les accords (environ 1 sur 2 est bien rendu).

**Comment by paternal** [comment]
J'ai réussi à faire l'analyse des accords de songs. Vu la documentation de PlasTeX, c'est quasimente de la rétroingénierie. C'est fait dans le commit [`9bb910b`](/patacrep/songbook-core/commit/9bb910b1b9868da18fc87a7c47900917deef511d).

J'ai juste fait l'analyse ; je ne sais pas comment vous souhaitez réutiliser cela.

L'analyse de PlasTeX produit un arbre de `Node`, correspondant à la structure du document LaTeX (par exemple, la phrase `Tagada \emph{Tsoin} Tsoin` sera décomposée en autant de `Node` que de lettres, sauf `\emph{…}` qui est un `Node` contenant un `Node` pour chacune des lettres). Ma rustine ajoute ce qu'il faut pour que les accords (par exemple `\[C]`) apparaissent correctement dans cette structure de document. Faites en ce que vous voulez !

Si vous ne savez pas comment faire pour utiliser ça, dites le moi, en précisant bien ce que vous voulez en faire.

**Comment by Luthaf** [comment]
Coool !

> Vu la documentation de PlasTeX, c'est quasimente de la rétroingénierie.

Oui, un poil ... Le logiciel est bien, mais la doc est pauvre ...

> Si vous ne savez pas comment faire pour utiliser ça, dites le moi, en précisant bien ce que vous voulez en faire.

Je vais essayer, en gros l’idée sera de parcourir les nodes pour faire la conversion

``` LaTeX
\begin{verse}
    His \[Dm]steely skin is covered
    By \[F]centuries of dust
    \[C]Once he was a great one
    \[Dm]Now he's dull and rust
  \end{verse}
```

en

``` HTML
<p class="verse">
    His <span class="chord"><span class="chord-name">Dm</span><span class="chord-text">steely</span></span> skin is covered
    By <span class="chord"><span class="chord-name">F</span><span class="chord-text">centuries</span></span> of dust
 ...
</p>
```

La principale difficulté va être de savoir comment découvrir les fins d'accords. Je pense que ca va être un certains nombre de caractères, ou d'espaces s'il n'y a pas de caractères.

**Comment by paternal** [comment]
> La principale difficulté va être de savoir comment découvrir les fins d'accords. Je pense que ca va être un certains nombre de caractères, ou d'espaces s'il n'y a pas de caractères.

Vu la [documentation de songs](http://songs.sourceforge.net/songsdoc/songs.html#sec5.3), je n'ai pas l'impression que ça sera compliqué : c'est soit un mot, soit quelque chose contenu entre deux accolades, mais ce dernier cas devrait apparaître comme un seul `Node` plasTeX.

Pour la production de HTML, va faire un tour du côté des _renderer_ (documentation [succinte](http://plastex.sourceforge.net/getting-started/) et [moins succinte](http://plastex.sourceforge.net/plastex/module-plasTeX-Renderers.html)).

**Comment by paternal** [comment]
Pour info, j'ai l'impression que seul le premier accord de chaque ligne est correctement rendu : http://songbook-web.tk/fr/songs/dessins-animes/asterix-et-cleopatre-le-pudding-a-larsenic/

**Comment by Luthaf** [comment]
Oui, il semblerai. Je n'ai pas beaucoup cherché pourquoi, c'est une version quick and dirty pour le moment.

**Comment by jmclem** [comment]
J'ai jeté un oeil; la regex dans `generator\songs.py` n'était pas suffisante. Je l'ai complétée, ça va mieux, mais il y a encore des cas à parfaire, mais peut-être plutôt côté html/css?

En particulier, les accords qui n'ont pas de texte associé (comme les premiers fa ici : http://songbook-web.tk/en/songs/la-maison-tellier/babouin/) sont affichés sur la ligne de chant, pas sur la ligne d'accords parce que le `<span class="chord-text">` est vide.

**Comment by Luthaf** [comment]
L'idée était plus de d'utiliser plasTeX pour le parsing, puis de mettre en cache le HTML généré. La solution à base de regex est temporaire et a vocation à dégager dès que plasTeX fonctionnera.

Il y a sans doutes aussi des améliorations à faire en terme de CSS/HTML en effet.

**Comment by oliverpool** [comment]
Coucou !
j'ai 5 min, et une rustine à vous proposer pour le CSS : 

```
main .chord-text:empty:after{
    content:"\00a0";
}
```

(si il n'y a rien dans `<span class="chord-text"></span>`, alors on force l'écriture d'un espace insécable - `&nbsp;` en HTML)

Cela permet d'afficher correctement les accords de début de ligne de http://songbook-web.tk/en/songs/la-maison-tellier/babouin/

**Comment by Luthaf** [comment]
Après quelques tentatives de mise en place de plasTeX, je me heurte à un problème. Le fichier est bien analysé, mais le contenu des accords apparait deux fois dans la liste des tokens : 

```
je \[G]prends \[G]Les rombières énamourées
```

devrait donner

```
je <chord>G</chord>prends <chord>G</chord>Les rombières énamourées
```

mais donne 

```
je <chord>G</chord>Gprends <chord>G</chord>GLes rombières énamourées
```

Les accords existant deux fois dans liste des nœuds. @paternal, sais-tu d'où cela peut-il venir ? J'ai jeté un œil à ton code, mais je ne voit pas ce qui pourrait clocher.

Sinon, les lignes ne sont pas respectées, ce qui est le comportement normal de LaTeX, mais pas pour les environnements `songs` où la macro `\obeylines` est utilisée. Je vais regarder si il y a moyen de modifier l'analyse effectué par plasTeX pour qu'il différencie ` `de`\n`.

**Comment by paternal** [comment]
C'est ajouté à ma todo liste.

**Comment by Luthaf** [comment]
Merci !

**Comment by Luthaf** [comment]
> Sinon, les lignes ne sont pas respectées, ce qui est le comportement normal de LaTeX, mais pas pour les environnements songs où la macro `\obeylines` est utilisée. Je vais regarder si il y a moyen de modifier l'analyse effectué par plasTeX pour qu'il différencie ` `de`\n`.

Alors j'ai commence a regarder ca, et il se trouve que l'on a besoin de modifier assez peu de choses pour le faire fonctionner. Il faut remplacer [cette ligne](https://github.com/tiarno/plastex/blob/master/plasTeX/Tokenizer.py#L392) de plasTeX par

``` Python
token = EndOfLine('\n')
```

Et il ne reste qu'une exception a rattraper [ici](https://github.com/patacrep/songbook-core/blob/next/songbook_core/plastex_songs.py#L56), qui est plus simple a gérer.

Je ne sais pas s'il y a plus simple pour pouvoir changer le comportement de plasTeX (par exemple charger notre propre classe `Tokenizer`).

EDIT: j'ai changé le nom de l'issue, il y en a déjà 4 avec song et parsing ...

**Comment by paternal** [comment]
> Les accords existant deux fois dans liste des nœuds. @paternal, sais-tu d'où cela peut-il venir ? J'ai jeté un œil à ton code, mais je ne voit pas ce qui pourrait clocher.

Je n'ai pas réussi à reproduire cela. @Luthaf, tu peux me fournir un exemple minimal ?

> [...] `\obeylines` [...]

Avec ta proposition (je n'ai pas testé ; dis moi si je me trompe), j'ai peur que ça ne change le comportement des fins de lignes _dans tous le document_. J'ai l'impression que le mieux serait de créer en PlasTeX la gestion de la commande `\obeylines` (ce qui ne semble pas être le cas). La définition de `\obeylines` est faite à partir de `catcodes` (**\def\obeylines{\catcode`^^M\active \let ^^M\par**) qui sont, selon mon impression, gérés par PlasTeX. La question est : Pourquoi PlasTeX ne prend pas en compte cette commande ?

J'ai l'impression que si tu as vu ces deux problèmes, c'est que vous avez commencé l'implémentation du rendu HTML à partir de l'arbre généré par PlasTeX. Pour que je puisse étudier tout ça, le plus simple est que je travaille avec cette même partie.
- Je vais installer et faire tourner songbook-web comme [décrit](/patacrep/songbook-web/wiki/Development-installation) (cette page est-elle toujours à jour ?).
- Pouvez-vous m'indiquer à quel endroit du code (branche, fichier, voire fonctions et lignes) du code ce rendu PlasTeX->html est-il fait ?
- N'importe quel fichier semble produire ces bugs. Vous confirmez ?

À vous de jouer !

**Comment by Luthaf** [comment]
> La question est : Pourquoi PlasTeX ne prend pas en compte cette commande ?

Parce que on ne lui a pas donné à manger le fichier de définition des environnements songs (songs.sty).

> Je vais installer et faire tourner songbook-web comme décrit (cette page est-elle toujours à jour ?).

Oui

> Pouvez-vous m'indiquer à quel endroit du code (branche, fichier, voire fonctions et lignes) du code ce rendu PlasTeX->html est-il fait ?

Dans [ce fichier](https://github.com/patacrep/songbook-web/blob/master/generator/songs.py#L77). Mais pour le moment, ce n'est que la solution à base de regex qui est utilisée. Je vais mettre en ligne une version plasTeX sur une branche séparée.

EDIT: fait, sur la branche plastex. 

> Je n'ai pas réussi à reproduire cela. @Luthaf, tu peux me fournir un exemple minimal ?

En fait, c'est de ma faute. J'utilisais deux générateurs différents, au lieu d'épuiser le même pour lire le contenu des accords. En gros tu n'as besoin de regarder que le problème de `\obeylines`, que je ne vois pas vraiment comment résoudre.

**Comment by paternal** [comment]
> > La question est : Pourquoi PlasTeX ne prend pas en compte cette commande ?
> 
> Parce que on ne lui a pas donné à manger le fichier de définition des environnements songs (songs.sty).

Ça m'a l'air d'être une excellente raison. Du coup, je propose quelque chose : 315915221ce241c4b7f6848fb360c48590c974e1. Ça charge un fichier [songs-minimal.sty](https://github.com/patacrep/songbook-core/blob/315915221ce241c4b7f6848fb360c48590c974e1/songbook_core/data/latex/songs_minimal.sty) qui contient le strict minimum pour inclure `\obeylines` au bon moment. Par contre, je n'ai pas pu le tester car je n'ai pas réussi à installer `django-background-task` : il n'est pas packagé dans Debian, et pip refuse de l'installer : 

```
$ pip install --allow-all-external django-background-task                                           
Downloading/unpacking django-background-task
  Could not find any downloads that satisfy the requirement django-background-task
  Some insecure and unverifiable files were ignored (use --allow-unverified django-background-task to allow).
Cleaning up...
No distributions at all found for django-background-task
Storing debug log for failure in ~/.pip/pip.log
```

**Comment by jmclem** [comment]
> pas réussi à installer django-background-task : il n'est pas packagé dans Debian, et pip refuse de l'installer

bizarre, je l'ai installé sans pb sous debian 7.4 / pip 1.1; quelle est ta version?

**Comment by paternal** [comment]
Debian testing / pip 1.5. Finalement, j'ai réussi à l'installer en téléchargeant le .zip à la main, puis avec `pip install <nom>.zip`.

**Comment by paternal** [comment]
@Luthaf : Il y avait bien un problème de chord qui apparaissait plusieurs fois. C'est corrigé (patacrep/songbook-core@950d9b36f8b765937270a79661df961f3e031d25), et ça s'utilise comme ça : 82c7ded7f75ab5830b21185c41447bfb4111c1d3.

Ma proposition pour `\obeylines` ne fonctionne pas. J'y retourne…

**Comment by Luthaf** [comment]
> @Luthaf : Il y avait bien un problème de chord qui apparaissait plusieurs fois. C'est corrigé (patacrep/songbook-core@950d9b3), et ça s'utilise comme ça : 82c7ded.

Cool, merci !

> Ma proposition pour \obeylines ne fonctionne pas. J'y retourne…

Bon courage ! Il faut peut-être lui donner à manger la définition de `\obeylines` au début du .sty ?

**Comment by paternal** [comment]
Je pense que le problème est résolu : patacrep/songbook-core@4244d9a1dd4ef1292d82e8015c8d5f0a6b71d10f.

Ensuite, dans [`parse_song()`](/patacrep/songbook-web/blob/82c7ded7f75ab5830b21185c41447bfb4111c1d3/generator/songs.py#L33-58), pour tester si un nœud donné est un retour à la ligne ou non, on fait le test `getattr(node, 'tagName', None) == 'active::\n':`.

En plus, je commencerais presque à comprendre ce que je fais avec PlasTeX…

**Comment by Luthaf** [comment]
> En plus, je commencerais presque à comprendre ce que je fais avec PlasTeX ...

 ^^ 
C'est quand même presque un parseur TeX complet ...

**Comment by oliverpool** [comment]
Désormais effectué par patacrep.
