### ISSUE TITLE
Regrouper les templates

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#17]
Pour le moment, on a plein de templates qui font la même chose, à savoir afficher un formulaire en changeant simplement le lien vers lequel il faut poster ce formulaire et le titre de la page. 

Ça pourrait être cool de tous les regrouper dans un fichier generic_forms.html et d'ajouter au contexte de chaque vue qui utilise ces formulaires trois variables : post_url, title et submit_name par exemple.

**Comment by oliverpool** [comment]
ca fait notamment parti du "design" : je me l'assigne !

**Comment by oliverpool** [comment]
Est-ce que https://docs.djangoproject.com/en/1.6/topics/forms/#displaying-a-form-using-a-template est suffisant ?

```
form.as_p will output the form with each form field and accompanying label wrapped in a paragraph.
```

**Comment by Luthaf** [comment]
Pas tout à fait : en fait il faut aussi que le template des formulaire comprenne une balise `<title>` ; un titre de page (pour l'instant dans le `<header>`) ; un petit nom au bouton submit et une URL vers laquelle envoyer les données

Ce à quoi je pensais : 

```
{% extends "generator/generator_base.html" %} {% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block headertitle %}{{ title }}{% endblock %}

{% block content %}
    <form method="post" action="{% url send_url %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{{ submit_value }}"/>
    </form>
{% endblock %}
```

Où les variables `title`; `send_url` et `submit_value`sont ajoutées au contexte de la vue. Soit en surchargeant la méthode get_context_data ; soit en ajoutant un dictionnaire à la vue dans le fichier `urls.py`

Après ce n'est utile que pour quelques formulaire sous cette forme là. Mais sans la variable `title`, on peut utiliser le template forms.html partout là où on a besoin d'un formulaire, avec `{% include generator/forms.html %}` par exemple.

**Comment by oliverpool** [comment]
Effectivement : ma remarque concernait seulement les formulaires, j'ai bien conscience qu'il faut faire un système de templates plus complet.

[Concernant l'url, elle va rarement être différente de celle de la page courante (à part pour la recherche, je n'ai pas d'exemple !)]

**Comment by oliverpool** [comment]
Ce n'est pas fondamentalement dramatique...(surtout que maintenant ils sont faits ses formulaires ;-)

**Comment by Luthaf** [comment]
Oui, c'est vrai, mais je suis un poil maniaque du rangement de code ^^

En effet on peut laisser tomber le regroupement, c'est aussi lisible comme ça (un template=une vue)
