### ISSUE TITLE
What next ?

### ISSUE THREAD

**Issue by jmclem** [patacrep/patanet#18]
Je crée cette issue sous forme de chat pour les discussions "à quoi je m'attaque maintenant".
Donc, "à quoi je m'attaque maintenant" ;) ? Je vois plusieurs pistes :
- interface web:
  - recherche par titre/artiste
  - sélection de chants
  - gestion des recueils
- moteur
  - lancer la compil sur le serveur
- site
  - tester le deployment sur un serveur web

En fonction de ce sur quoi vous bossez déjà, qu'est-ce qui vous paraît pertinent d'attaquer ?

**Comment by Luthaf** [comment]
Je suis déjà sur la partie gestion des receuils/sélection de chants/compil sur le serveur (qui se suivent en fait : si je peut sélectionner mes chants puis écrire la liste dans les .sb, alors je peut compiler le PDF !)

Il faudrait peut-être aussi faire la partie gestion des fichiers .sg : 
- Enregistrement dans git, 
- Import des fichiers dans la base (sous la forme d'une VersionedFileField par exemple)
- Affichage sur l'interface web (avec parsing des fichiers .sg en .html)
- (Édition depuis l'interface web)

Pour moi c'est le problème suivant à gérer.

**Comment by jmclem** [comment]
ok, voir [#19](../issues/19)

**Comment by jmclem** [comment]
Nous avons les fonctionnalités principales (gestion des chants, des carnets, des utilisateurs, génération des PDFs). 

Je trouverais bien de s'acheminer vers une version fonctionnelle, même si elle ne contient pas certains autres aspects 'chics'. J'ai modifié le [wiki](https://github.com/patacrep/songbook-web/wiki/Status) en conséquence. 

Si vous êtes d'accord, je peux alors m'attaquer soit à la gestion des fichiers PDFs (servir, supprimer) soit commencer à regarder pour le déploiement.

**Comment by Luthaf** [comment]
Je pense que tu seras le plus compétent parmi nous pour gérer le déploiement, donc je veux bien te laisser faire =)

**Comment by Luthaf** [comment]
Ca vaut vraiment le coup de laisser cette issue ouverte ?
