### ISSUE TITLE
password-reset-do

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#20]
Ce n'est pas possible de mettre des parametres GET dans les regexp de url.py
reset-password-do?uid=(?P<uidb36>.+)&token=(?P<token>.+)
=> reset-password-do
et dans la vue request.GET.get('uid')

**Comment by Luthaf** [comment]
Là c'est moi qui me suis planté : en fait les paramètres GET sont récupérés automatiquement : 

Dans le fichiers urls.py il faut mettre 

```
url(r'^user/reset-password-do$', 
```

Et tout ce qui est à la fin d'une URL et après un '?' est automatiquement mis dans le dictionnaire request.GET

Désolé, ça fait partie des trucs que je n'ai pas trop testés ...

**Comment by oliverpool** [comment]
pas de soucis (c'est juste que je viens de tester toutes les vues, donc j'ai découvert quelques petits bugs désormais corrigés)
