### ISSUE TITLE
Email vs Username

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#21]
Je suis assez partisan d'utiliser l'email comme identifiant

**Comment by jmclem** [comment]
je préfère aussi. Les login_id, c'est une chose de plus à oublier avec le mdp ;)

**Comment by Luthaf** [comment]
Pourquoi pas. Il faudrai peut-être alors modifier la phase d'inscription en ajoutant une validation d'adresse mail.

**Comment by Luthaf** [comment]
J'ai un poil regardé, et il y a ça qui a l'air pas mal : 
http://www.micahcarrick.com/django-email-authentication.html

Je suis même pour permettre une identification mixte, avec soit l'adresse mail, soit le nom d'utilisateur. Ça ne doit pas être trop compliqué (en gros modifier un poil la méthode `authenticate`)

Si ça vous va, je peut m'en charger.
