### ISSUE TITLE
Template refactoring

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#22]
Je restructure actuellement les templates : push à venir !

**Comment by oliverpool** [comment]
J'ai regroupé dans un sous-dossier "layout" les templates qui ne sont pas directement référencées dans views.py

Code de base :

```
{% extends "generator/layout/full_layout.html" %}{% load i18n %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
on the website
{% endblock %}
```

Le titre de la fenêtre est automatique : Titre - Songbook-web
Pour personnaliser le début, utiliser le block 'headertitle'
Pour personnaliser l'ensemble, utiliser le block 'windowtitle'

**Comment by Luthaf** [comment]
Cool ! Je vais jeter un œil plus tard, mais ça a l'air plus organisé déjà !

Après dans l'optique de distribuer le bazar comme une application Django 'plugable', on peut peut-être déplacer les templates dans un sous dossier templates du module generator, non ?

Du style : PROJECT_ROOT/generator/templates/generator/...

**Comment by oliverpool** [comment]
L'arborescence m'est bien égale...
Je suis en train de réfléchir à un design plus orienté recueil (le wikipédia était centré "chanson")
