### ISSUE TITLE
Design orienté Receuil

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#23]
Je créé une nouvelle issue car j'ai dévié l'issue #22...

Donc je propose ici un design (plus pertinent ?) centré sur les recueils !

J'ai dans l'idée de faire 2 colonnes:
- à gauche le "catalogue" des chansons
- à droite le recueil actuel

L'idée globale est de faire un style de lecteur de musique avec playlist (= recueil) à droite.

La colonne de gauche afficherai soit les artistes, soit les chansons d'un artiste, soit le résultat de la recherche (soit le contenu d'un autre recueil)
Des checkbox permettent de choisir d'ajouter au receuil en cours un sélection de chansons/d'artisites

La colonne de droite est assez similaire : les cases permettent de supprimer des chansons du receuil
Quelques liens supplémentaires redirigent vers les options ou la compilation

**Comment by Luthaf** [comment]
Yeh ! C'est pas mal comme idée !

J'ai une question liée, je la pose à la bonne place (#8)

**Comment by jmclem** [comment]
Hmmm, je vois bien un joli drag n' drop pour emmener les chants de la colonne de gauche dans la composition du recueil et pour les y ordonner.

**Comment by oliverpool** [comment]
@jmclem : tout à fait ;-) (ca va nécéssiter pas mal de JS-AJAX)

Du coup dans la liste des recueils, il vaut mieux mettre des cases avec le rang des chansons

**Comment by Luthaf** [comment]
Au passage, un petit lien sur l'intégration d'AJAX dans Django :
http://tutos-django.com/2012/03/04/un-formulaire-sexy-en-ajax/

En fait ça a l'air relativement simple à mettre en place =) 
(Moi qui croyais que l'AJAX c'était super complexe ...)

**Comment by oliverpool** [comment]
Le seul truc spécifique à Django est le "request.is_ajax()" pour retourner du JSON, le reste est assez classique (la partie "complexe" JS est gérée par jQuery dans l'exemple que tu as donné)

C'est notamment pourquoi je suis assez partant pour utiliser jQuery

**Comment by Luthaf** [comment]
Que compte-tu mettre dans la div playlist ? Un truc du genre

```
{% for song in songbook %}
<li>
    <label class="artist" title="{{ song.artist }}">
        {{ song.title }}
    </label>
</li>
{% endfor %}
```

**Comment by oliverpool** [comment]
tout à fait
Avec quelques "décorations":
- un input à gauche pour le rang
- une croix de suppression à droite
- un bouton pour aller voir les paroles
- ...

**Comment by oliverpool** [comment]
Après avoir pas mal bataillé avec Python, j'ai enfin réussit à éviter que le code `try ... catch` (destiné à inclure le carnet en cours sur la droite) soit dupliqué dans plusieurs fonctions !
J'ai donc créé un décorateur `@render_with_current_songbook`  qui se charge de ce travail (10f55031ce)

Edit : réflexion faite, j'aurai plutot du l'appeler `@context_with_current_songbook`...

**Comment by Luthaf** [comment]
> Edit : réflexion faite, j'aurai plutot du l'appeler @context_with_current_songbook...

Ou `@add_current_songbook_to_context`. Dans tous les cas on peut encore le modifier =)

Tes modifs sont encore une fois plutôt cools pour le design ! Concernant l'affichage du carnet, je pensait à un truc : ça serait cool si on faisait un affichage par sections, avec la liste des chants dans une section qui soit 'pliable'. Je sais que c'est possible à faire en CSS ou en JS, et je me demandais : 
- Quelle était la meilleure manière de faire
- Comment devais s'organiser le code HTML pour ce faire.

**Comment by oliverpool** [comment]
C'est une bonne idée et c'est tout à fait faisable, relativement facilement en CSS pur.
Code html que j'utiliser habituellement:

```
<label for="section_1"><h4>Titre de la section 1</h4></label>
<input type="checkbox" name="section_1" class="section_checker" />
<ul class="section">
<li>...</li>
</ul>
```

Avec le CSS:
- on cache la checkbox (display:none): un clic sur le titre de la section continuera de cocher/décocher la case
- on affiche l'élément HTML qui suit si la case est cochée (le type d'élémen importe peut : ol,ul, div...)

PS : le fonctionnement actuel me convient assez: vous faites les fonctionnalités et j'essaye de les mettre en forme ;-)

**Comment by Luthaf** [comment]
Je viens de le mettre en place (99ed52adcc1a3e1c42b3716931ab95f2c3321d3e), à toi la main !

Au passage, pour avoir un code HTML plus compact tout en restant lisible dans les templates, on pourrai utiliser la balise [`{% spaceless %}`](https://docs.djangoproject.com/fr/1.6/ref/templates/builtins/#spaceless)

**Comment by oliverpool** [comment]
Effectivement: j'ai cherché sans trouvé un tel outil...je vais donc l'utiliser quand nécessaire !

**Comment by Luthaf** [comment]
> on affiche l'élément HTML qui suit si la case est cochée (le type d'élémen importe peut : ol,ul, div...)

Faut-il nécessairement que tout soit inclus dans un élément HTML ? (je suppose que oui ...)
Parce qu'avec la nouvelle manière de faire pour gérer les sections, j'ai du mal à gérer la fermeture des balises dans le cas où on a plusieurs sections ... 

En fait c'est bon (f8200ee71a6a6378b425e7cbf82c5052bb918139) ! Je voulais à tout pris le faire depuis le template ...

**Comment by oliverpool** [comment]
Est-ce qu'il y a vraiment besoin d'imbriquer tout cela dans du HTML hiérarchisé ?
Je verrai bien un truc purement linéaire 

```
<li class="section">Section-Titre<li>
<li class="song">Chant</li>
<li class="song">Chant</li>
<li class="section">Section-Titre<li>
<li class="song">Chant</li>
<li class="song">Chant</li>
<li class="song">Chant</li>
```

Certes c'est sémantiquement moins précis, mais ca correspond au rendu final : une suite linéaire d'éléments !

Ca permet aussi une très grande souplesse : on peut rajouter des sous-sections, on peut mettre une liste principale de chants sans section (donc forcément la première : par exemple je souhaite regrouper les chants "à boire" à la fin du carnet, je n'ai pas besoin d'une première section)...

**Comment by Luthaf** [comment]
> Ca permet aussi une très grande souplesse  : on peut rajouter des sous-sections, on peut mettre une liste principale de chants sans section (donc forcément la première : par exemple je souhaite regrouper les chants "à boire" à la fin du carnet, je n'ai pas besoin d'une première section)...

Effectivement, ça serait plus souple. Après si on a 100-150 chants par carnet (c'est mon cas), c'est pas plus mal de les afficher/masquer par section. Concernant le fait que la première section n'est pas forcément au début du carnet, c'est normalement géré par la version actuelle.

**Comment by oliverpool** [comment]
Afficher/masquer par section peut très bien être fait via JS

**Comment by oliverpool** [comment]
Différenciation de la sélection courante et du carnet

Je m'explique :
- à droite, le cadre vert est juste destiné à "faire ses courses". On va chercher des chants dans le site et on les ajoute "au panier". Peut-être faudrait-il seulement afficher ici les chants triés alphabétiquement ou par artiste (pas besoin de sections ou d'ordre qui surchargent l'affichage)
- sur la page "carnet xxx", là on souhaite "organiser son panier". C'est là qu'on va ordonner les chants, créer les sections et régler les paramètres avant la génération (on peut donc afficher plus d'info est permettre plus de réglages)

**Comment by Luthaf** [comment]
Je sais pas. J'aime bien avoir l'ensemble de la structure sous les yeux pour ma part.

Que mettrais-tu dans la sélection courante ?

(mais j'aime bien l'analogie !)

**Comment by oliverpool** [comment]
*sélection courante
En gros il y a tous les chants du carnet, mais l'ordre n'est pas modifiable (par exemple trié par auteur ou titre) pour savoir rapidement si un chant manque au carnet ou pas

**Comment by Luthaf** [comment]
OK. Je persiste à préférer un affichage des chants dans l'ordre défini par l'utilisateur (donc avec des sections) : c'est un avis personnel mais je m'y retrouve mieux si il y a beaucoup de chants. De toute manière, les chants présent dans le carnet sont affichés dans la liste (case cochée).

Par contre en effet dans la sélection courante il est sans doutes mieux de ne pas pourvoir modifier cet ordre. C'est comme ça que j'étais partis d'ailleurs : avec une vue spécifique pour le _tri du panier_ et la suppression de chants ; et les vues existantes (liste de chants et vue d'un chant) pour ajouter des chants au carnet.

**Comment by oliverpool** [comment]
Ok, on part là dessus.
Pour le "triage" des chants, plutôt que d'avoir une case à cocher (pour la suppression) et un numéro (pour l'ordre), on fusionne le tout dans "un numéro" et si celui-ci vaut "-1", le chant doit être supprimé du carnet (ce traitement peut être rapidement implémenté en JS avec une zone "corbeille")

**Comment by oliverpool** [comment]
@Luthaf : ok, du coup on garde l'affichage de la sélection courante telle qu'elle sera dans le carnet.
En revanche je me suis permis de retirer le bouton d'ajout de section de cette sélection (69cf36de7)

**Comment by Luthaf** [comment]
Question : le fichier boilerplate.less sera-t-il utilisé ?

**Comment by Luthaf** [comment]
Je crois que tous les éléments ont a présent un style. C'est fortement améliorable, mais c'est déjà ça =)
Si vous voyez des choses aberrantes, dites le moi, sinon je fermerai cette issue.
