### ISSUE TITLE
Import du langage des chants

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#24]
Il semble avoir un problème à l'import des langages : à la langue french est associé le code french, et non pas fr comme espéré.

Mais cela m'amène à me poser la question de l'utilité du code de la langue pour ce site web en fait ...

**Comment by jmclem** [comment]
Oui, c'est juste, ça manque encore; il y a un FIXME dans le code. Je m'attaque à ça alors (j'avais différé ;) )

Lequel attends tu ? `fr` ou `fr-FR` ?

**Comment by Luthaf** [comment]
OK =)

En fait je ne sais pas si ce code est utile ... Je ne me souviens plus pourquoi je l'avais mis, sans doutes par habitude ... De toute façon il ne sert qu'à deux choses : 
- indiquer à Babel quelle est la langue courante lors de la compilation
- effectuer une recherche par langue.

**Comment by jmclem** [comment]
J'ai fait la modif. En fait, django inclus les listes de langages (`django.conf.global_settings.LANGUAGES`). J'ai donc viré notre table Language et utilisé seulement le code correspondant. Pour l'instant, on a `en`, `fr`, `pt`, `es`

**Comment by Luthaf** [comment]
Ok, parfait !
Par contre ça ne pose pas de problème pour l'instant, il faudra voir si on a un jour des chants dans une langue un poil plus exotique, mais toutes les langues ne sont pas représentées dans `django.conf.global_settings.LANGUAGES`
