### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#25]
Voici ce que je propose pour la pagination:
- les listes complètes (artistes & chansons) sont paginées par lettre (j'ai une classe python sous le coude ;-)
- les chansons par artiste ne sont pas paginées (c'est n'est pas très utile, je connais peu d'artistes avec trop de chansons)

Si vous êtes ok, je code ça !

**Comment by Luthaf** [comment]
J'approuve, j'allais ouvrir cette issue un de ces quatres ^^

**Comment by oliverpool** [comment]
Une dépendance en plus:
 unidecode
(pour transformer les caractères unicodes en caractère ASCI au plus proche)

**Comment by Luthaf** [comment]
Ok, c'est cool pour la pagination !

Quand à unidecode, c'est de toute manière déjà une dépendance du moteur =)

**Comment by Luthaf** [comment]
Juste deux questions : 
- Serait-il possible de mettre plutôt les numéros après les lettres ? C'est un peu étrange que la page par défaut de "tous les artistes" ou de "toutes les chansons" soit celle des artistes/chansons commençant par des chiffres.
- Et à quoi sert le paramètre `paginate_by` dans ce cas ? Ou une autre manière de formuler ma question, comment est géré le cas de (très) nombreuses chansons commençant toutes par la lettre A ?

**Comment by oliverpool** [comment]
En gros les lettres sont regroupées jusqu'à atteindre `paginate_by` :
- si A et B on 10 artistes, les lettres sont regroupées pour avoir un bloc à 20 artistes si `paginate_by > 20`
- si il y a 50 artistes en A, ils sont tous affichés sur la page de A (mais sans autre lettre)

**Comment by Luthaf** [comment]
Ok, parfait ! Et pour les chiffres, c'est modifiable ?
(j'avoue, j'ai la flemme d'aller voir le code en détail ...)

**Comment by oliverpool** [comment]
yep, je regarde ça

**Comment by Luthaf** [comment]
Cool ! J'aime bien tes modifs sur les artistes et nombre de chansons aussi =)
