### ISSUE TITLE
Pages statiques

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#27]
Bon, il va aussi y a voir sur le site un ensemble de pages statiques : 
- Toute la section **contribuer**
- une page **à propos**
- des pages d'exemples
- Je pensais aussi à une page "Comment fabriquer un carnet" pour donner des idées de création de carnet depuis le PDF (reliure, ...)

Bref, vous m'avez compris. La question est alors comme va-t-on gérer ces pages ? Je vois deux solutions : 
- Envoyer des pages fixes _via_ le mécanisme de gestion des fichiers statiques (css, js)
- Utiliser l'application [flatpage](https://docs.djangoproject.com/fr/1.6/ref/contrib/flatpages/) de Django

Qu'en pensez-vous ?

**Comment by oliverpool** [comment]
Les pages fixes via fichier statique peuvent poser un problème de traduction ? (et de dynamisme pour la barre "compte utilisateur" ?)

**Comment by Luthaf** [comment]
Je pense que la meilleur solution est en effet l'application flatpage avec mise en cache des zones dynamiques à l'échelle du site. Mais il faut envisager toutes les options =)

**Comment by jmclem** [comment]
Ça peut être fermé ?

**Comment by Luthaf** [comment]
Pas vraiment : il faut encore écrire toutes ces pages. Comme pages a rédiger, je vois : 
- contribuer
- a propos
- une FAQ
- des mentions légales
- la page d’accueil

Quoi d'autre ?

**Comment by Luthaf** [comment]
Après quelques recherches, il semble compliqué de traduire les pages statiques avec flatpages. Il y a d'autres apps qui permettent de faire le boulot ([celle-là](https://github.com/PragmaticMates/django-flatpages-i18n) qui a plein de dépendances ou [celle-ci](http://code.google.com/p/django-multilingual/) qui n'est plus maintenu), mais rien qui ne m’aie convaincu.

Les solutions que je vois pour garder un site international : 
- Utiliser flatpage avec une page par par langague, indiquée par son URL (`/en/about/`, `/fr/about/`, etc.)
- Créer notre propre modèle de page statiques avec une app pour la traduction (comme [ça](https://pypi.python.org/pypi/django-translatable/0.1.1) ou [ça](http://code.google.com/p/django-multilingual-model/) ou [ça](https://github.com/deschler/django-modeltranslation))
- Utiliser des TemplateView pour gérer les pages statiques.

La dernière solution est la plus simple, il faut juste écrire les URLs pour chaque page.

**Comment by Luthaf** [comment]
Finalement, les pages statiques sont gérées avec une `TemplateView`, et peuvent donc avoir une URL de la forme `/fr/pages/FAQ/` et être traduites. Les URLs sont vérifiées automatiquement, tout fichier placé dans `templates/generator/pages/` sera transformé en page statique. 

Il est aussi possible de créer une page statique à une autre adresse (voir par exemple la page d’accueil du site).

J'ai commencé à rédiger certaines pages, mais il va falloir continuer ! Tout commentaire est apprécié =)

**Comment by Luthaf** [comment]
Et on continue à remplir les pages (58563fc1100a606d4086bdc1195c66aefc2cfc3a). Il ne reste plus que : 
- Des mentions légales
- La page d'accueil

**Comment by Luthaf** [comment]
Terminé ! 1f0e0ec3758d4f77866bd084643dd140b366e34d et b44bc3d89969d013a3bf11ac87ad13487da8ab67.
