### ISSUE TITLE
Carnets ou receuils ? => Carnets

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#28]
Une petite question pour garantir la cohérence dans les noms : doit-on parler de carnets, de carnets de chants, de recueils, de recueils de tablatures, ou employer un autre nom ?

Pour ma part, je préfère l'expression carnet ou carnet de chants.

**Comment by oliverpool** [comment]
Effectivement, c'est à décider !
Je suis d'accord avec toi : carnet ou carnet de chants me convient (et dans tous les cas, 'songbook' en anglais)

**Comment by jmclem** [comment]
Carnet de chants me va bien.

On 2 février 2014 14:56:51 UTC+01:00, oliverpool notifications@github.com wrote:

> Effectivement, c'est à décider !
> Je suis d'accord avec toi : carnet ou carnet de chants me convient (et
> dans tous les cas, 'songbook' en anglais)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Luthaf/songbook-web/issues/28#issuecomment-33900838

## 

Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.
