### ISSUE TITLE
Interoperabilité avec git

### ISSUE THREAD

**Issue by jmclem** [patacrep/patanet#3]
Y-a-t-il déjà des idées de la manière dont la repo va être gérée depuis l'app en python? Si non, j'ai fait quelques recherches ;)
Il y a un fil ici : http://stackoverflow.com/questions/1456269/python-git-module-experiences
Quelques modules relevés (sur la base des commentaires, j'en ai testé aucun):
- [GitPython](https://gitorious.org/git-python)
- [Gittle](https://github.com/FriendCode/gittle) et/ou [Dulwich](http://www.samba.org/~jelmer/dulwich/docs/)
- L'utilisation du package sh me paraît aussi pas mal ([ici](http://stackoverflow.com/questions/1456269/python-git-module-experiences#8578096))

Ajoutez les idées/commentaires/essais.

**Comment by Luthaf** [comment]
Je n'avais pas du tout regardé ça, je pensais faire des appels systèmes ^^ Merci !

Gittle à l'air bien, la doc des autres est plus difficile à trouver. Gittle fournit un accès direct aux diverse versions des fichiers depuis python, ce qui est cool =)

**Comment by oliverpool** [comment]
(j'avais aussi imaginé des appels systèmes...)

**Comment by Luthaf** [comment]
Je viens de trouver ça, qui m'a l'air de fournir tout ce dont nous avons besoin pour gérer de manière transparente ou presque des versions de fichiers depuis Django : https://pypi.python.org/pypi/django-vff

Vous en pensez-quoi ? Ça m'a l'air plutôt bien =)

**Comment by jmclem** [comment]
oh yeah ! ça à l'air bien adapté, je jette un œil dqp!

**Comment by oliverpool** [comment]
les exemples sont effectivement élégants !
