### ISSUE TITLE
Choix de l'architecture AJAX/JS

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#32]
Voici le message original de jmclem

  ================================

Ok ! Maintenant, mettre du JS, ça implique des choix.
1. sur l'architecture et les APIs web
2. d'un framework

Aujourd'hui, le ReST est très largement appliqué pour l'AJAX. 
- Soit on le suit, c'est une garantie de propreté concernant les APIs web. 
- Soit on s'attache à qqc d'autre (pas d'idée). 
- Soit on ne s'occupe pas de suivre une telle 'specification', avec le risque d'avoir des APIs dégue à la fin.

Plus d'infos sur [wikipedia](http://fr.wikipedia.org/wiki/Ajax_%28informatique%29) et à plein d'autres endroits. Il y a aussi au moins un composant [ReST pour Django](http://www.django-rest-framework.org/)

Pour le framework JS, jquery et ExtJS sont parmis les plus connus; j'ai déjà utilisé jquery (il y a qq temps déjà).

**Comment by Luthaf** [comment]
Concernant ReST, je ne suis pas sûr de bien comprendre le fonctionnement. En gros Django-rest nous permet de gérer la sérialisation/désérialisation des objets ; et les différents types de requêtes : POST, GET, PUT, DELETE, PATCH, ...

Y a-t-il d'autre points de différence ?

**Comment by jmclem** [comment]
> Y a-t-il d'autre points de différence ?

avec quoi ?

ReST est une manière de concevoir des APIs qui fait appel aux verbes HTTP. En gros (il y a des variations dans l'interprétation):
- get : lire
- post : créer
- delete : supprimer
- put : modifier

L'API est sous forme d'urls, qui n'ont rien à voir avec les urls du site. Ils sont destinés à l'API et sont habituellement appelés par des scripts (JS). Ça _pourrait_ donner pour nous:`

```
GET /site.com/song (retour : liste des chants)
GET /site.com/song/45 (retour : le chant d'id 45)
PUT /site.com/song/45 (avec infos en JSON ou XML pour mettre à jour le chant d'id 45)
DELETE /site.com/song/45
POST /site.com/song (créer un nouveau chant, avec les infos envoyées en JSON ou XML)
```

Pour atteindre cela, il faut:
1. pouvoir sérialiser/déserialiser les objets et les listes d'objets
2. gérer et interpréter les URLs de l'API

C'est ce que django-Rest aide à implémenter.

**Comment by Luthaf** [comment]
Ok ! Par contre ça exige de réécrire un poil les quelques vues actuelles =) Mais pourquoi pas en effet. 

EDIT : je ne suis pas forcément pour utiliser django-rest pour les réponses get en fait, ça ne semble pas très pratique pour customiser le rendu HTML. Pour les autres pourquoi pas.

**Comment by oliverpool** [comment]
Je pense qu'on va un peu vite:
JavaScript != AJAX 

Il n'est utile de faire une API (REST ou non) que si on fait de l'AJAX (c'est à dire, prise en compte des actions utilisateurs sans rafraichissement complet de la page)
Si on rajouter juste du JS (pour le glisser-déposer par exemple), une telle API est inutile.

En revanche, si on veut ajouter un chant au carnet dès que la case est cochée (sans attendre un clic sur "Ajouter au carnet"), alors là c'est utile.

Concernant l'API (communication avec le serveur), on peut tout simplement utiliser le lien de Luthaf : http://tutos-django.com/2012/03/04/un-formulaire-sexy-en-ajax/

```
if request.is_ajax():
    errors = json.dumps(form.errors)
    return HttpResponse(errors, mimetype='application/json')
```

C'est à dire que les URL restent identiques, mais que si c'est appelé via Ajax, on retourne un objet JSON à la place de la vue HTML

Une API en béton est utile si on souhaite interfacer d'autres systèmes avec le site web (application smartphone, site web externe)

Concernant le framework c'est une autre question (qui mérite effectivement d'être posée)

**Comment by Luthaf** [comment]
Effectivement, si on peut juste avoir quelques vues avec de l'AJAX et du JS un peu partout, moi ça me va !

Pour le Framework, je n'ai pas d'avis.

Pour l'AJAX, quelles sont les vues où cela serait utile ? Je met celles auxquelles je pense, avec un ordre de priorité (1 très important - 3 peu utile)
- La vue d'une chansons pour ajouter/supprimer un chant sans rafraichir (2)
- Le tri des chansons d'un carnet (1)
- Les listes de chants pour ajouter supprimer plusieurs chants sans rafraichir (2)
- La connexion/déconnexion des utilisateurs sans quitter la page courante (3)

**Comment by oliverpool** [comment]
> - Le tri des chansons d'un carnet (1)

C'est surtout le JS qui est important (pour le glisser-déposer), selon moi l'Ajax est secondaire (d'ailleurs je suis même plutôt contre, car un rafraichissement de la page atteste **visuellement** de la prise en compte du tri effectué par l'utilisateur)

> - La vue d'une chansons pour ajouter/supprimer un chant sans rafraichir (2)

Je le mettrai même en n°1 : on coche la case / on clic sur le bouton et la chanson apparait directement dans "carnet en cours"

> - Les listes de chants pour ajouter supprimer plusieurs chants sans rafraichir (2)

Tout à fait d'accord pour attribuer la même priorité que le point précédent

> - La connexion/déconnexion des utilisateurs sans quitter la page courante (3)

Quitte à faire cela, autant faire l'ensemble de la navigation en Ajax...
Autre argument contre : après le login, on peut afficher une page personnalisée avec les dernières modifications des chants des carnets de l'utilisateur, les nouvelles chansons depuis sa dernière connexion...

**Comment by jmclem** [comment]
> Je pense qu'on va un peu vite:
> JavaScript != AJAX

Tu as raison, j'ai assimilé les deux dans mes interventions, mea culpa. Pour préciser ma pensée : je suis pour l'AJAX à plein d'endroits.

> ```
>    Le tri des chansons d'un carnet (1)
> ```
> 
> C'est surtout le JS qui est important (pour le glisser-déposer), selon moi l'Ajax est secondaire (d'ailleurs je suis même plutôt contre, car un rafraichissement de la page atteste visuellement de la prise en compte du tri effectué par l'utilisateur)

J'ai du mal à te suivre, là. Justement pour le tri manuel, j'aurais mis de l'AJAX, parce que l'affichage correspond à une modification qui doit être répercutée sur le serveur. À quel moment communiques-tu le nouveau tri sans cette communication ?

**Comment by Luthaf** [comment]
Avec un bouton "envoyer" qui envoie la liste en POST au serveur. Si j'ai tout bien compris, la liste  ressemble avant modifications à 

```
<label for="section1">Ma section</label><input id="section1">1</input>
<label for="chant4">Chant 4</label><input id="chant4">2</input>
<label for="chant83">Chant 83</label><input id="chant83">3</input>
<label for="chant62">Chant 62</label><input id="chant62">4</input>
<label for="chant274">Chant 274</label><input id="chant274">5</input>
```

Avec du JS et du drag & drop, on transforme cette liste en :

```
<label for="chant4">Chant 4</label><input id="chant4">1</input>
<label for="section1">Ma section</label><input id="section1">2</input>
<label for="chant274">Chant 274</label><input id="chant274">3</input>
<label for="chant62">Chant 62</label><input id="chant62">4</input>
<label for="chant83">Chant 83</label><input id="chant83">5</input>
```

Puis on envoie l'ensemble de la liste au serveur qui la met à jour et affiche de nouveau la liste ordonnée si toutes les modifs ont été prise en compte. Corriges-moi si je me plante @oliverpool

**Comment by oliverpool** [comment]
@Luthaf c'est exactement ce que j'avais en tête
(avec une correction de syntaxe : `<input type="number" id="chant4" value="1" />`)

@jmclem  Certes avec de l'Ajax on peut synchroniser en direct ces modifications, mais cela comporte quelques points négatifs:
- l'Ajax doit être assez robuste pour fonctionner même en cas de connexion instable (et signaler si la connexion est perdue)
- ça augmente le trafic avec le serveur (une action utilisateur => une requête AJAX)
- ça peut être perturbant pour l'utilisateur de ne pas avoir de bouton "sauvegarder mon tri" (mais avec un design bien pensé et des bons messages, ça peut être super agréable à utiliser)

**Comment by jmclem** [comment]
C'est vrai, ça peut marcher comme ça aussi.

Ça peut aussi, par extension, plus tard sans doute, faire l'objet d'un envoi non pas systématique, mais régulier vers le serveur de manière asynchrone : toutes les N secondes, si la liste a été modifiée, elle est envoyée sur le serveur et un message discret s'affiche du genre "tous les changements ont été sauvegardés sur le serveur".

**Comment by Luthaf** [comment]
> Ça peut aussi, par extension, plus tard sans doute, faire l'objet d'un envoi non pas systématique, mais régulier vers le serveur de manière asynchrone : toutes les N secondes, si la liste a été modifiée, elle est envoyée sur le serveur et un message discret s'affiche du genre "tous les changements ont été sauvegardés sur le serveur".

Ça me va comme fonctionnement. Si je récapitule, on peut partir sur : 
- Un entier comme index
- Un tri manuel de liste avec JS/Drag'n drop
- Dans le cas où JS est désactivé, un tri en affectant des numéros à chaque chants
- Un bouton de tri automatique pour le [tri par auteur](https://github.com/Luthaf/songbook-web/issues/30#issuecomment-34424427) à l'intérieur des sections
- À terme, une sauvegarde régulière automatique.
- De l'AJAX pour l'ajout/suppression de chants depuis les listes de chants/d'auteurs.

Si ça va à tout le monde, je continuerai à faire quelques vues liées à la gestion des carnets (liste des chants du carnet)

**Comment by oliverpool** [comment]
La feuille de route de Luthaf me convient.

Je me suis fait une autre réflexion dernièrement : différencier la sélection courante et le carnet. Je développe l'idée dans #23

**Comment by jmclem** [comment]
> Dans le cas où JS est désactivé, un tri en affectant des numéros à chaque chants

je mettrais ce dev à la fin et à la condition que le besoin s'en fasse sentir. Sinon, c'est ok.

**Comment by Luthaf** [comment]
> > Dans le cas où JS est désactivé, un tri en affectant des numéros à chaque chants
> 
> je mettrais ce dev à la fin et à la condition que le besoin s'en fasse sentir. Sinon, c'est ok.

Pour moi c'est surtout un effet de bord : pour que JS fonctionne, il a besoin de petits cadres avec un numéro à rentrer. Ces cadres sont masqués à l'utilisateur, et remplis automatiquement par JS. Donc si il n'y a pas de JS, c'est l'utilisateur qui rempli les cases. Il faut juste que les cases soient masquées par JS et pas par défaut.

**Comment by oliverpool** [comment]
@Luthaf :+1:

**Comment by jmclem** [comment]
Je ne vois pas d'effet de bord ; je vois une chose de plus à prendre en compte, à tester et à débugger. Le but de ma remarque était de se concentrer sur une ligne de dev qui permette d'avoir une version fonctionnelle et de repousser une fonctionnalité secondaire, voire inutile, à plus tard. Mais si vous avez le temps pour ouvrir un truc de plus, allez-y.

**Comment by Luthaf** [comment]
En fait je ne vois pas comment faire autrement qu'en utilisant un `<imput>` pour le rank ...

**Comment by jmclem** [comment]
Tu peux avoir en JS des objets complètement indépendants du DOM et générer des éléments dans le DOM à partir de ces objets. Tu n'est pas obligé de stocker tes données dans le DOM.

**Comment by Luthaf** [comment]
Ok. Ce n'est pas malgré tout plus simple si les infos sont dans le DOM ? 

J'y vois au moins un avantage pour moi : ça me permet de faire des tests sans avoir à écrire les fonctions JS ^^

**Comment by jmclem** [comment]
> infos sont dans le DOM

en général on évite et on cherche là aussi, à l'intérieur du navigateur, à respecter le MVC, donc une séparation des données et de leur vue.

**Comment by Luthaf** [comment]
Et du coup, de quelle manière on transmet les données à JS ?

**Comment by jmclem** [comment]
Par une requête AJAX/AJAJ. De même pour l'écriture.

**Comment by oliverpool** [comment]
> on cherche là aussi, à l'intérieur du navigateur, à respecter le MVC, donc une séparation des données et de leur vue.

Pour moi cela concerne surtout une application entièrement en JS (avec un framework type Backbone, Angular, Ember...)
Pour moi la ligne de conduite est plus d'utiliser JS pour améliorer le site web:
http://en.wikipedia.org/wiki/Progressive_enhancement 
vs 
http://en.wikipedia.org/wiki/Unobtrusive_JavaScript#Degrading_gracefully, http://en.wikipedia.org/wiki/Graceful_degradation

**Comment by Luthaf** [comment]
>  Pour moi la ligne de conduite est plus d'utiliser JS pour améliorer le site web:

Je partais aussi plus sur quelque chose comme ça. Quel sont les avantages d'utiliser de l'AJAX/AJAJ ici ?

**Comment by oliverpool** [comment]
Je viens de me faire une remarque concernant l'ergonomie: 
c'est pas évident/agréable de faire du drag'n'drop sur des listes avec des centaines d'éléments... (même sur un écran tactile)
La solution avec numéro de rang permet de déplacer efficacement un chant à un nouveau rang !
(en autorisant l'utilisateur à mettre des nombres décimaux pour insérer entre des chants)

**Comment by Luthaf** [comment]
Pas faux ... Du coup l'utilisateur édite manuellement les rangs ? 

Ce qui pourrait être cool, c'est d'avoir les deux : un drag'n drop et une édition manuelle des rangs. Comme ça c'est confortable à la fois pour des petits déplacements (drag'n drop) , et pour des grands (modification manuelle du rang). De plus, en JS il doit être possible de déplacer un élément dès que l'utilisateur rentre un nouveau numéro, non ? 

Pour l'insertion, c'est plus simple si l'utilisateur rentre un entier correspondant au futur rang du chant je pense. Exemple : j'ai la liste suivante : 

```
1 chant4
2 chant76
3 chant8
4 chant835
```

et je veux mettre le dernier chant en second : je rentre donc 2 comme numéro pour ce chant, et JS se charge de me décaler le reste : 

```
1 chant4
2 chant835
3 chant76
4 chant8
```

**Comment by jmclem** [comment]
> Quel sont les avantages d'utiliser de l'AJAX/AJAJ ici ?

Je ne pense pas qu'on puisse parler d'avantages ou d'inconvénient; c'est plutôt conditionné à ce qu'on envisage pour la partie client de l'application (dans le navigateur), et on envisage(ait) pas la même chose.

>    Pour moi la ligne de conduite est plus d'utiliser JS pour améliorer le site web:
> Je partais aussi plus sur quelque chose comme ça.

C'est ok, de toute façon, c'est vous qui le faîtes :)

**Comment by oliverpool** [comment]
C'est pas mal en effet que les deux "modes d'éditions" (drag'n'drop, numérotation manuelle) soient en temps réel

**Comment by jmclem** [comment]
Si je résume : oui pour JS, non pour AJAX à grande échelle.
