### ISSUE TITLE
Gestion des permission

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#33]
Comme on a commencé à en discuter un poil [ici](https://github.com/patacrep/songbook-web/commit/a01c2b8aa2cb1efb669f6f65c54880468fc77ec3), il faudrait implémenter une gestion des permission : créer des carnets, modifier des carnets, créer des chansons, modifier des chansons, etc.

**Comment by oliverpool** [comment]
Je propose simplement:
Chansons:
- voir : visiteur & +
- créer et modifier (& commit auto): utilisateur enregistré

Carnet:
- voir : visiteur si public, propriétaire (unique) sinon
- créer et modifier : propriétaire

Pas de propriétaires multiples, pas de partage restreint de carnet (les mails/facebook permettent d'envoyer un pdf très efficacement...)

**Comment by Luthaf** [comment]
> Pas de propriétaires multiples, pas de partage restreint de carnet (les mails/facebook permettent d'envoyer un pdf très efficacement...)

C'est vrai que c'est un poil inutile comme fonctionnalité ... À la base je l'avais mis pour permettre des partages entre plusieurs créateurs sur un même carnet, mais il est possible d'utiliser un même compte pour plusieurs.

**Comment by oliverpool** [comment]
> utiliser un même compte pour plusieurs

oui, et dans ce cas, c'est même mieux d'être physiquement à côté ! (parce sinon il faudrait aussi un système de commentaires & co...)

**Comment by Luthaf** [comment]
Question à ce propos : faut-il laisser le modèle `Profile` ? Il peut servir à étendre les attributs du modèle `User` mais il ne nous sert plus à rien si on a pas de partage des carnet. Sauf si on envisage l'ajout d'avatars, d'adresses web perso, etc.

**Comment by oliverpool** [comment]
je pense qu'on peut le laisser (au cas où), mais il faudrait lier les carnets à un utilisateur plutôt
(il y a notamment un bug avec l'admin, dont le profil n'est pas créé ! - et qui donc ne peut pas avoir de carnet...)

**Comment by Luthaf** [comment]
> il y a notamment un bug avec l'admin, dont le profil n'est pas créé ! - et qui donc ne peut pas avoir de carnet...

C'est corrigeable avec l'utilisation de signaux.
Edit : fait (5a1849ce0174c439ed99633721ecc95b41858a8b)

> il faudrait lier les carnets à un utilisateur plutôt

Pourquoi pas, mais il faut alors faire un poil plus de refactorisation du code.

**Comment by Luthaf** [comment]
Pour l'implémentation, le plus simple doit être d'utiliser le décorateur [`@user_pass_test`](https://docs.djangoproject.com/en/dev/topics/auth/default/#limiting-access-to-logged-in-users-that-pass-a-test). Avec ça il n'est pas nécessaire d'ajouter une app supplémentaire comme django-guardian. 

Et je pense que ça peut faire l'affaire tant que l'on a pas grand chose d'autre à gérer comme permission par objet.

**Comment by oliverpool** [comment]
> Pour l'implémentation, le plus simple doit être d'utiliser le décorateur [`@user_pass_test`](https://docs.djangoproject.com/en/dev/topics/auth/default/#limiting-access-to-logged-in-users-that-pass-a-test). 

Apparemment on ne peut pas lire `request` dans la fonction de test : http://stackoverflow.com/questions/11872560/how-to-pass-django-request-object-in-user-passes-test-decorator-callable-functio

**Comment by Luthaf** [comment]
~~Non, mais ce n'est pas grave : le décorateur utilise directement l'objet user. En tout cas ça a l'air de marcher dans ce cas : 
http://bradmontgomery.blogspot.co.uk/2009/04/restricting-access-by-group-in-django.html~~

Edit : je viens de comprendre ce que tu as dis ... On ne va pas couper à django-guardian alors =)

**Comment by oliverpool** [comment]
ou alors on reste en mode "bricolage" (il n'y a pas beaucoup de cas d'utilisation, que `owner` si ?)

django-guardian, c'est peut être un peu lourd comme artillerie, pour contrôler l'accès à un seul objet (le songbook) à un utilisateur unique (le propriétaire).

On peut juste faire un décorateur `owner_or_public` à utiliser sur les chants privés (si on les implémente un jour ;)

**Comment by Luthaf** [comment]
C'est aussi une solution. Mais j'aime bien le concept de Django : un problème = une app ^^

Il n'est pas toujours nécessaire de réécrire la roue, mais en effet, on est pas obligé de sortir la chenille de tank pour faire avancer notre vélo

_(c'était ma minute métaphores étranges !)_

**Comment by oliverpool** [comment]
Parce du coup si on résume, on doit gérer les cas suivants:
- public
- accessible aux utilisateurs connectés (mon profil/mes carnets)
- accessible seulement au propriétaire (modifier un carnet par exemple)
- accessible selon les droits de l'objet : propriétaire uniquement, ou public (consulter un carnet)

Même à l'avenir, je ne vois pas d'autre cas de figure (à moins qu'on se lance dans le carnet collaboratif...ce qui n'est pas vraiment à l'ordre du jour ;-)

Au niveau des décorateurs:
- public => rien à faire
- connectés => `@login_required`
- propriétaire => à faire, `@owner_required` qui vérifie une méthode `object->is_owned_by(user)` par exemple 
- propriétaire ou public (object-dependent) => à faire,  `@owner_maybe_required` qui vérifie une méthode `object->is_public or object->is_owned_by(user)` par exemple 

Ayant juste deux cas à gérer, ça ne devrait pas nécessiter une app aussi complète que django-guardian ^^

_(et j'aime bien tes métaphores)_

**Comment by Luthaf** [comment]
J'ai commencé à faire ça (d1eb00a34966579f9f89707e597c103d31f51c6f). Ça a l'air de marcher, mais il y a un truc qui me chiffonne un peu : pour l'instant, on décore directement les classes, et non pas une fonction. Le problème est qu'alors on ne peut pas utiliser ces décorateurs pour les fonctions comme `move_or_delete_items`, etc.

Mais je ne sais pas comment accéder au carnet avec un décorateur de fonction.

**Comment by oliverpool** [comment]
Effectivement c'est un problème...

Soit on fait deux décorateurs (un de fonction, un de classe)
Soit on détecte le type d'objet décoré dans le décorateur (_code incomplet, je ne sais pas si c'est faisable/pertinent de faire ça en python_):

```
def owner_or_is_public(to_decorate):
    def dispatch_wrapper(function):
        def check_access(self, *args, **kwargs):
            songbook = to_decorated.get_object(self)
            return access(function, request.user, songbook)
        return check_access

    def access(self, function, user, songbook):
            if songbook.is_public:
                return function(self, *args, **kwargs)
            elif songbook.user == user:
                return function(self, *args, **kwargs)
            else:
                return redirect(reverse('denied'))

    dispatcher = getattr(to_decorate, "dispatch", None)
    if callable(dispatcher):
        to_decorate.dispatch = dispatch_wrapper(dispatcher)
        return to_decorate
    else:
        return ...
```

**Comment by Luthaf** [comment]
Je pensais plutôt a utiliser un décorateur de fonction, et l'appliquer a la méthode `dispatch`. Mais de cette manière, je n'arrive pas a récupérer l'instance songbook. Il faudra peut-être la passer en paramètre au décorateur.

**Comment by oliverpool** [comment]
Sinon on peut transformer ces fonctions en classes `ActionView` (<= classe à créer ou alors on utilise `DetailView`)
On implémente une méthode `get_object()`
Et on implémente l'action (suppression, autre) dans disptach (qui renvoie alors une redirection)

(du style de `DeleteSongbook`, mais on implémente un méthode dispatch personnalisée)

**Comment by Luthaf** [comment]
Je ne suis pas fan. Ça m'a l'air moins clair comme code que la version actuelle. Sinon, il semble possible d’écrire un décorateur mixte pour fonctions et méthodes (http://stackoverflow.com/q/2589690). Je vais creuser un peu le sujet.

**Comment by oliverpool** [comment]
Je reconnais que c'est pas hyper clair, mais on a toujours le même schéma:
1. récupérer un objet (ou 404)
2. vérifier les droits (ou login_required / access denied)
3. faire quelque chose (`set_current_songbook`, `add_songs_to_songbook`, `move_or_delete_item`
4. rediriger vers une `next_url`

Avec un vue générique, on a juste à gérer le 3ème point

**Comment by oliverpool** [comment]
_lui aussi mérite un `@owner_required` :
https://github.com/patacrep/songbook-web/blob/master/generator/views.py#L443_

**Comment by Luthaf** [comment]
OK, je vois mieux ce que tu veux dire. Du coup je suis pour remplacer `ItemsListInSongbook` et `move_or_delete_items` par une seule vue basée sur UpdateView, avec un [formset](https://docs.djangoproject.com/en/dev/topics/forms/formsets/#formsets) de `ItemInSongbook`. Comme ça le dernier formulaire permet de rajouter une section, et les autres de modifier l'ordre.

Par contre pour `add_songs_to_songbook`, il n'y a pas de vue associée ... Du coup je propose simplement de gérer a la main les autorisations dans le corps de la fonction. Ou alors on la transforme en UpdateView aussi, mais alors sans avoir de version GET.

**Comment by oliverpool** [comment]
ok, UpdateView à l'air pertinent.

`add_songs_to_songbook` c'est peut-être mieux de faire une vue sans GET ...
Sinon on pourrait fusionner avec `set_songbook` : si c'est un GET, c'est pour sélectionner le songbook (et donc redirection quand même), si c'est un POST, on ajoute les chants au carnet.
C'est un peu du bricolage, mais sémantiquement ça se tient : dans les deux cas on ajoute(ra) des chants au carnet!

**Comment by Luthaf** [comment]
Pourquoi pas.

Je reste quand même dubitatif pour ce que cela nous apporte. Un décorateur plus approprie (avec comme paramètre songbook_id) est plus simple et plus lisible. Mais je vais faire des tests.

**Comment by Luthaf** [comment]
Définitivement, décorer des classes n'est pas la meilleur solution : la méthode a décorer change selon la classe : `get_object` ou `get_queryset`. 

Je vais passer le tout avec un décorateur de la forme `@owner_required(songbook_id)`

**Comment by Luthaf** [comment]
Après quelques tests (de django-guardian entre autres), je ne vois toujours pas comment faire : 
- si on a que des vues basées sur des classes, la méthode a décorer change à chaque fois, et il est compliqué d'accéder de manière unique à l'identifiant du carnet. La solution peut-elle venir des Mixins ?
- Si on a les deux (fonctions et classes), on a encore ce problème d'accès au carnet.
- Django-guardian est peut-être la solution, mais il semble planter sur les bords (j'ai l'autorisation d'accéder à une page sans avoir affectée cette autorisation ...)

En tout cas, à demain pour de nouvelles aventures !

**Comment by Luthaf** [comment]
Quelques commentaires sur le code : on peut utiliser soit les décorateurs `@owner_required` et `@owner_or_public_required` pour les vues basées sur des fonctions, et les mixins `OwnerRequiredMixin` et `OwnerOrPublicMixin` pour les vues basées sur des classes.

Il y a aussi le mixin `LoginRequiredMixin` qui peut être utile.

**Comment by oliverpool** [comment]
Je ne connaissais pas les mixins (comme beaucoup d'autres choses en python...), mais ça à l'air d'être bien adapté !

**Comment by Luthaf** [comment]
Je les ai découvert en faisant mes recherches pour ce problème =)

Et c'est plutôt funky en effet !
