### ISSUE TITLE
Design : création d'un logo

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#34]
Tout est dans le titre ^^

Quelqu'un veut-il s'en charger, ou bien je lance une amie graphiste amateur sur le sujet ?

**Comment by jmclem** [comment]
Pas moi, c'est pas mon truc !

**Comment by oliverpool** [comment]
c'est pas mon truc non plus...
Peut-être qu'un message sur le cercle scout serait pertinent ?

**Comment by Luthaf** [comment]
Je peut poser la question à la personne que je connais, et en fonction de sa réponse ou en parallèle on peut poser la question sur FB.

**Comment by oliverpool** [comment]
ou organiser un concours ;-)

**Comment by oliverpool** [comment]
On peut aussi donner des idées au(x) designer(s) pour ce que le logo doit/ne doit pas mettre en avant. Je pense à des thèmes et des mots qui décriraient le site web:
- musique, chansons
- guitare
- scout, veillée
- communautaire
- LaTeX
- carnet
- ...

**Comment by Luthaf** [comment]
J'ai rédigé un petit document pour décrire les termes d'un concours à lancer sur FB. 
Vous en pensez quoi ? Il est [là](https://gist.github.com/Luthaf/b1060ce009e4404c436e).

**Comment by jmclem** [comment]
Bonne initiative ! Je pense qu'il serait bénéfique d'ajouter une intro ciblant l'initiative.

Début de proposition, à modifier ad lib :

> Créer son propre carnet de chants facilement, à partir d'une base de chants pré-existants ou de ses propres saisies, n'est-ce pas le rêve de tout guitariste/musicien/responsable de groupe ? C'est ce que nous pensons, et nous travaillons à la création d'une application web pour réaliser ce rêve : vous sélectionnez dans une liste autant de chants que vous le voulez, vous les ordonnez, choisissez un format et ... récupérez un PDF que vous pouvez imprimer, partager, ... Si, si, ça va exister :)
> Ceci dit, nous sommes des développeurs, et si nos doigts sont agiles sur un clavier, ils deviennent très gauches sur une tablette graphique. Nous voilà donc bien mal lotis dans notre désir d'avoir une application non seulement utile, mais aussi agréable et jolie. C'est pourquoi nous appelons À L'AIDE !!!

**Comment by Luthaf** [comment]
Mis a jour !

Avez-vous une idée des autres icônes qui pourraient être nécessaires ?

**Comment by Luthaf** [comment]
Publié sur FB ! Plus qu'a attendre les retours =)

**Comment by Luthaf** [comment]
Bon, un mois après, je n'ai pas eu de retours ... C'est un peu un échec ^^

Des idées pour trouver un logo ? Dans le pire des cas, je peux bricoler quelque chose =)
