### ISSUE TITLE
Que faire du moteur

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#37]
Où met-on le moteur ? Pour l'instant il est dans un sous-module git, mais certaines personnes semblent réticentes à l'utilisation de sous-modules. 

Pour moi les deux options sont
- Un sous-module git que l'on conserve à la version compatible. C'est peut-être plus complexe à utiliser mais on est sur d'avoir exactement le commit que l'on veux
- Laisser l'utilisateur choisir ou est le moteur, avec le risque de plantages dans le cas où il y a une mise à jour entre temps.

**Comment by jmclem** [comment]
Je propose de partir sur des repos distinctes et d'identifier les commits du moteur qui fonctionnent avec l'interface web par le hash ou par des labels.

**Comment by Luthaf** [comment]
Pourquoi pas. Il faudrait ajouter une vérification du label alors dans l'import du moteur.

**Comment by oliverpool** [comment]
@Luthaf pourquoi le sous-module est plus complexe à utiliser ?

Sinon on peut dire que le moyen 'officiel', c'est d'utiliser le sous-module git, mais en laissant une variable CORE_PATH, pour que les utilisateurs expérimentés puissent choisir une version du moteur différente si besoin

**Comment by Luthaf** [comment]
>  pourquoi le sous-module est plus complexe à utiliser ?

C'est ce qui est sorti dans [cette](http://www.patacrep.com/forum/viewtopic.php?pid=790#p790) discussion sur le forum.

Moi ca m'avait l'air pas trop mal, on gère justement les versions compatibles ou non, l'utilisation d'une branche ou d'une autre, ... C'est pour ca que je pose la question ici !

**Comment by paternal** [comment]
J'ai mis en place un installateur [ici](https://github.com/patacrep/songbook-core/commit/5d3bbd92f34b1d594787be9792f05363beab7b1d). Avec ça, j'ai l'impression que la question posée dans ce ticket ne se pose plus : on instale songbook (avec `python setup.py`, ou en installant un [paquet debian](https://github.com/patacrep/songbook-core/tree/next#quick-and-dirty-deb-packages)), et ça roule : un `import songbook_core` fonctionnera, sans avoir besoin d'un submodule git, ou de modifier le PYTHONPATH.

Je propose donc la fermeture de ce ticket.

**Comment by Luthaf** [comment]
Cet installeur permet de gerer les version ? Du style songbook-web est compatible avec la version 3.7.2, 3.8 mais pas 3.8.1 ? Si c'est le cas, fermons !

**Comment by paternal** [comment]
Hé bien avec git, tu te place sur le tag 3.8 (et non pas 3.8.1), tu génères ton deb, que tu installes. Et voilà.

Je ne suis pas sûr d'avoir répondu à ta question…

**Comment by Luthaf** [comment]
Oui, en effet, il suffit d'avoir accès aux anciennes version ! 

Ca me va comme fonctionnement alors.

(vive git pour le coup ^^)
