### ISSUE TITLE
User interaction with PDF generation process

### ISSUE THREAD

**Issue by jmclem** [patacrep/patanet#38]
Discussion commencée [ici, #8](https://github.com/patacrep/songbook-web/issues/8#issuecomment-35830580)

**Depuis quel endroit l'utilisateur va-t-il déclencher le traitement du carnet vers un PDF?**

Je propose d'avoir un bouton/lien "Générer PDF" ou équivalent
- sur la page du carnet
- sur l'encart "carnet en cours" (current songbook)
- sur la liste des carnets, un pour chaque carnet.

Une fois l'action déclenchée, l'utilisateur est redirigé vers la page du carnet.

**Comment allons nous rapporter à l'utilisateur le déroulement du processus de génération du carnet ?**

Les possibilités :
- Les liens/boutons utilisés ci-dessus se transforment en affichage d'information (queued, processing) puis en lien vers le fichier avec une action possible "supprimer"
- on envoit un email une fois le travail fini avec un lien vers le fichier

**Comment by oliverpool** [comment]
> l'utilisateur est redirigé vers la page du carnet.

C'est à dire qu'on lui demande les derniers paramètres du carnet (accords & co.) [je préfère ça], ou que tu commence véritablement la génération pdf ?
Si c'est le premier cas, je nommerai le lien plutôt "Télécharger le carnet en pdf"

Sur cette page de "génération", on pourrait afficher les fichiers déjà compilés et encore téléchargeables (avec date de compilation)

---

Pour le déroulement du processus, je verrai bien une checkbox "envoyer le carnet généré par courriel" (du coup l'utilisateur est prévenu de la fin de la compilation, et a une sauvegarde de son carnet ;-)

Sinon, un affichage du statut (sous forme de "checklist": queueing, processing...) lorsque l'utilisateur recharge la page (ou via AJAX dans un futur procher :)

**Comment by jmclem** [comment]
> C'est à dire qu'on lui demande les derniers paramètres du carnet (accords & co.) [je préfère ça], ou que tu commence véritablement la génération pdf ?

Hmm, tu as raison, il y avait ça aussi :) Je dois dire que, comme ça transparaîtra dans d'autres contributions de ma part ce matin, j'ai envie de m'orienter sur un feature freeze pour stabiliser ce que nous avons et essayer de le déployer sur un serveur. Mais tu as raison, on pourrait inclure quelques petites options pour la génération du carnet.

**Comment by Luthaf** [comment]
Je suis pour un bouton "générer ce carnet" uniquement sur la page des carnets et la liste des carnets, avec une petite boite d'infos sur l’état de la génération.

**Comment by Luthaf** [comment]
Je propose (je ne sais pas trop où le mettre, ici me semble bien) de stocker les PDF dans  MEDIA_ROOT. Comme ça on a une URL directement : `media_url/PDF/<songbook>.pdf`. 

Et on peut ajouter deux champ à Songbook : `pdf_file` de type FileField, et gen_date de type date. Comme ça on peut : 
- Récupérer le chemin vers le PDF
- Savoir si le PDF existe
- Savoir quand il a été généré
- Gérer finement la suppression (toutes les semaines, tous les mois, ...)

Le contre-coup est qu'il ne peut y avoir qu'une seule version (= 1 seul Layout) par carnet généré. Sinon, on peut ajouter un modèle `CompilatedSongbook` de la forme : 

```
pdf_file = FileField
gen_date = DateField
songbook = FK(Songbook)
layout = FK(Layout)
```

(une sorte de many2many de Songbook sur Layout)

**Comment by Luthaf** [comment]
Bon, finalement, la discussion sur les layouts est sur l'issue spécifique (#36), et les liens ont été ajoutés de partout. Les informations sont affichées à l'utilisateur depuis la liste de ses carnets.

Les comits correspondants : b1f5cdf4fae54d070e5afa1a480a71617b41324b, 7417687f8aa56bc274a4d56620bca051c5cf4b9b et f496db6f3d69adcb2bb6b7a2e8563de85e24d71a
