### ISSUE TITLE
Serving PDF files to users

### ISSUE THREAD

**Issue by jmclem** [patacrep/patanet#39]
Quel procédé allons nous utiliser pour la mise à disposition des PDFs ?

Statique :
- directement par le serveur web
- utilise des URLs complexes pour éviter l'accès facile à des données de tiers
  Dynamique
- passe par django, qui retourne le contenu du PDF via le content/content-type
- utilise l'authentification django pour restreindre l'accès (NB : empêche le partage!)

Je penche pour le statique.

**Comment by Luthaf** [comment]
Je suis pour le statique aussi, mais sans URL complexes et avec authentification. Si besoin cela pourra évoluer, mais si les gens veulent partager leurs PDF, ils ont des mails.

**Comment by paternal** [comment]
Il est peut-être pertinenent de jeteur un œil à [Pyromaths](http://pyromaths.org/enligne/) pour voir comment ils font : c'est du Python qui sert sur le web du PDF compilé à partir de LaTeX. Ça ressemble donc pas mal à songbook-web.

**Comment by Luthaf** [comment]
Pyromath a l'air de fonctionner à base de POST : l'utilisateur envoie un formulaire, et le site renvoie un pdf comme réponse. Mais on a pas de sauvegarde des données envoyées, ni du PDF généré. Donc ce n'est sans doutes pas le plus adapté ici.

**Comment by Luthaf** [comment]
Finalement, le fonctionnement actuel me va pas mal aussi : la mise à disposition se fait par le site web uniquement, sans authentification, mais comme les fichiers seront supprimés régulièrement (cf #40), le risque de DDoS est relativement faible. On pourra ajouter un envoi de mail lorsque le fichier est prêt, avec une option lors de la création du Layout.

Si ça va à tout le monde, on peut fermer.
