### ISSUE TITLE
Guitar-tabs to songtex.js

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#4]
J'ai eu besoin d'écrire aujourd'hui un script pour convertir des accords écrits dans du texte brut en latex (du moins le plus gros du travail : "descendre" les accords).

J'ai donc créé un script JS pour faire le boulot : https://github.com/oliverpool/guitar-tabs_songtex.js (demo : http://codepen.io/anon/pen/fdczb)

**Comment by Luthaf** [comment]
Trop cool ! Dans l'exemple, ça ne semble pas marcher sur les premières lignes.

C'est facilement utilisable à l'envers comme code ?

**Comment by oliverpool** [comment]
Codepen a refusé ma mise à jour...voici donc une version correcte : http://codepen.io/anon/pen/fdczb

**Comment by oliverpool** [comment]
"C'est facilement utilisable à l'envers comme code ?"
Oui, pour quel usage ? 
Si c'est pour le site web j'ai une meilleure idée (parce que sinon ca impose une police de caractère à espacement fixe)

**Comment by Luthaf** [comment]
Oui, c'était pour le site web.

J'attends de voir l'idée alors =)
