### ISSUE TITLE
Delete PDF files after a given period

### ISSUE THREAD

**Issue by jmclem** [patacrep/patanet#40]
Quelle politique appliquons nous pour la suppression des fichiers PDFs ?

On pourrait garantir une dispo de disons une semaine et supprimer de temps en temps tous les fichiers plus vieux que cette période?

**Comment by oliverpool** [comment]
Idée: lors de la génération d'un nouveau, on vérifie les autres carnets déjà généré, et on, supprime les carnets obsolètes (en gros, si personne ne génère de nouveaux pdf, on garde les pdf actuels)

On pourrait mettre deux limites : nombre de PDF stockés et durée de conservation d'un pdf
(la première règle étant appliquée quoiqu'il arrive, pour éviter d'exploser la capacité de stockage)

**Comment by jmclem** [comment]
> Idée: lors de la génération d'un nouveau, on vérifie les autres carnets déjà généré, et on, supprime les carnets obsolètes (en gros, si personne ne génère de nouveaux pdf, on garde les pdf actuels)

donc on garde une version d'un carnet (la dernière), c'est ça? 

Finalement, c'est un choix que l'on devrait laisser à l'admin, non? Il devrait pouvoir configurer son site pour "conserver tous les pdfs" ou "conserver que les n derniers" et "pour une durée de xxx" ou "indéfiniment".

**Comment by Luthaf** [comment]
En effet. On peut aussi proposer une option "conserver N PDF par utilisateur"

**Comment by Luthaf** [comment]
Du coup, de quelle manière tient-on les comptes des PDF ? En allant lire le système de fichier, avec un champ en BDD ? Pour la BDD, ça pourrait se faire en ajoutant une entrée lors de la compilation PDF avec le lien vers le `Songbook` correspondant, un lien vers le fichier correspondant et la date de création. Puis un processus indépendant se charge de lire cette base et de supprimer les fichiers régulièrement. Cela permettrai aussi facilement d'avoir la liste des PDF correspondant à un carnet (#39) pour les donner aux utilisateurs.

**Comment by Luthaf** [comment]
Je propose d'utiliser les `tasks` pour tenir ces comptes. À savoir, on ajoute deux champs dans le modèle  : 
- Un hash du content + Layout, pour savoir si un carnet a déjà été compilé avec ce Layout
- Une date de dernière modification.

Un "carnet" correspondant à un fichier PDF : Layout + Content. 

Là dessus, on ajoute simplement une commande `clear_pdf`, qui se charge d'aller voir si les PDF doivent ou non être supprimés, puis qui supprime les fichiers et les entrées en BDD. Les réglages se font avec `SONGBOOK_DELETE_POLICY` un dictionnaire qui contient tous les réglages : 
- `mode` : `time` ou `by_user` ou `total_number` ;
- `expiration_time` 0 pour l'infini, sinon un timestamp, défaut 0 ;
- `number`: nombre de carnets à conserver par utilisateur/au total. Défaut -1 (= tous)

En mode `by_user` ou `total_number`, les carnets les plus anciens son supprimés en premiers. Qu'en pensez-vous ?

**Comment by jmclem** [comment]
Tu veux dire ajouter les deux champs au modèle `Task`, c'est bien ça ? Ça me paraît jouable.

**Comment by Luthaf** [comment]
C'est ça. Plus un script (utilisable avec crontab par exemple) qui se charge de supprimer les carnets.

**Comment by Luthaf** [comment]
En fait, après réflexion, je ferais bien ça un poil différemment. J'ajouterai bien 3 champs au modèle : 
- `hash` qui contient un hash de `Songbook` + `Layout`, ce qui permet de recompiler un carnet si le contenu ou la mise en page ont changés, ou de servir le fichier déjà compilé si rien n'a changé.
- `last_modified` qui est un champ de type date
- `layout` qui est une `ForeingKey` vers le modèle `Layout`. Ce modèle est conservé en BDD, ce qui permet à un utilisateur d'utiliser plusieurs fois la même mise en page pour divers carnets, et de partager cette mise en page. Je développe ce point sur l'issue dédiée (#36). 

Globalement, l'intégralité de cette gestion sera donc mise en place après le modèle `Layout`, donc pour la 0.2.

**Comment by Luthaf** [comment]
Commencé dans le commit 1454fea0731a237235ccb7dbcbab96f243dbbbf0. Les PDF sont à présent regénérés si le contenu a changé.
