### ISSUE TITLE
Premiere beta !

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#41]
J'ouvre cette issue pour discuter de ce qui doit être inclus dans la première version. 

Pour ma part, je verrais bien : 
- L'envoi des PDF aux utilisateurs (#39)
- Un poil de design en plus (#23)
- Les permissions (#33)
- Un poil de refactor pour la création d'un nouveau carnet.
- Quelques unes des pages statiques (#27)
- L'affichage a l'utilisateur du contenu des chants (en utilisant #15)

Qu'ai-je oublie/mis en trop ?

**Comment by paternal** [comment]
Hors sujet : Utilise un milestone plutôt qu'un ticket pour ça, non ? Ça semble plus approprié…

**Comment by jmclem** [comment]
J'ai assigné les issues qui me paraissent correspondre à la [milestone 0.1](https://github.com/patacrep/songbook-web/issues?milestone=1&state=open)

**Comment by Luthaf** [comment]
> Hors sujet : Utilise un milestone plutôt qu'un ticket pour ça, non ? Ça semble plus approprié…

Je n'ai pas l’impression que l'on puisse discuter de ce qu'il est ou non pertinent d'inclure sur une Milestone.

**Comment by paternal** [comment]
Effectivement : pas moyen de discuter d'un milestone. C'est fort dommage.

Au temps pour moi.

**Comment by Luthaf** [comment]
Alors, comme je commence à en avoir marre que cette première version soit à portée de main sans être accessible, je propose d'accélérer un peu les choses avec ce plan d'attaque : 
- Résoudre les dernières issues liées à la 0.1 (design et envoi des PDFs), à l’exception de #15. À la place, utiliser **temporairement** le script JS pour l'affichage des chants. 
- Remplir la page d’accueil avec les conditions d'utilisation de la beta.
- Recruter des gens via FB et le forum Patacrep pour participer à cette beta.
- Avoir plein de retours et corriger des bugs
- Boire un café et s'attaquer à la 0.2

Pour les règles d'utilisation, dans mon esprit ça donnait quelque chose comme [ce gist](https://gist.github.com/Luthaf/753731b71a4b5bcce45e). Et je pensais ouvrir la beta à un petit nombre de personnes, entre 5 et 10 dans un premier temps (si on a tout ça de réponses !). Quel est votre avis sur cette question grave ?

**Comment by jmclem** [comment]
Ça me va tout à fait, faut se lancer, je suis d'accord - même si j'ai peu de temps en ce moment. Je pense que l'on peut même prendre plus de testeurs, ou alors en plusieurs "fournées" : une série qui essuie les premiers plâtres, puis en inviter d'autres.

**Comment by Luthaf** [comment]
Je vais tenter de terminer tout ça d'ici la fin du WE alors ! Dès que le serveur ne renverra plus d'erreurs 500 (cf FB) aussi ^^

**Comment by Luthaf** [comment]
Première beta lancée, à cette adresse : http://songbook-web.tk/ !
