### ISSUE TITLE
Mise en cache

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#44]
Comment allons-nous gérer la mise en cache du site ? Django propose plusieurs [possibilités](https://docs.djangoproject.com/en/dev/topics/cache/). Parmi celles-ci je retiens les suivantes : 
- Sur le système de fichier pour les fichiers PDF ;
- Dans la RAM pour les pages web (avec un découpage entre les parties spécifiques à l'utilisateur et le contenu). C'est particulièrement pour moi particulièrement important pour l'affichage des chansons qui nécessite de parser les fichier .sg ;
- Dans la BDD : ce n'est pas vraiment une mise en cache pour ce qui nous intéresse, mais les pages statiques (#27) sont  par défaut dans la base de donnée. On peut laisser les choses comme ça, ou bien utiliser des TemplateView pour les pages statiques, et les gérer à la main.

**Comment by Luthaf** [comment]
En lien avec la mise en cache, je viens de tomber sur ce lien : http://sametmax.com/mode-le-manifeste-du-cache-du-mode-hors-ligne-pour-html5/. Ca pourrait valoir le coup aussi, une fois le dev presque fini.

**Comment by Luthaf** [comment]
Update : 
- Les fichiers PDF sont sur le système de fichier, la gestion du cache est manuelle (#40)
- Les pages statiques sont finalement des templates View, que l'on peut mettre en cache dans la RAM comme le reste si besoin.

Reste donc à mettre en place la mise en cache des contenus. Quels sont selon vous les contenus intéressants à mettre en cache ? Je vois : 
- Le contenu des chants
- Les menus utilisateurs
- Les listes de carnets, publics ou privés

**Comment by jmclem** [comment]
À mon avis, c'est la performance qui guide. Donc pour moi, tant qu'il n'y a pas de lenteur avérée, je ne vois pas la nécessité de mettre en cache. 

Si on veut vraiment peaufiner dès maintenant, il faudrait faire des mesures de perf d'abord.

> Le contenu des chants

peut-être, voir la perf ;)

> Les menus utilisateurs

je ne vois pas ce que tu veux dire

> Les listes de carnets, publics ou privés

j'ai le sentiment que ça change trop vite pour que le cache ait un intérêt quelconque.

**Comment by Luthaf** [comment]
En effet, cela peut attendre que le site soit trop lent pour être utilisé =)

> > Les listes de carnets, publics ou privés
> 
> j'ai le sentiment que ça change trop vite pour que le cache ait un intérêt quelconque.

Pas forcément sur une seule session, et il y a pas mal d'appels à la BDD pour les former.

**Comment by Luthaf** [comment]
Du coup, je ferme. On verra quand le site sera en prod.
