### ISSUE TITLE
Faire mention de la licence

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#47]
Il faudrait faire mention de la licence. Quelle est la meilleur manière de faire ? Ajouter un header à tous les fichiers, ou faire référence à un fichier spécifique ?

Sinon, tout le monde est bien d'accord pour utiliser la même licence que songbook-core, à savoir la GPLv2 ?

**Comment by Luthaf** [comment]
C'est fait pour les fichiers python. Pensez-vous que cela vaut aussi le coup pour les fichiers CSS et HTML ?

**Comment by paternal** [comment]
> Sinon, tout le monde est bien d'accord pour utiliser la même licence que songbook-core, à savoir la GPLv2 ?

Je propose plutôt (mais faites comme bon vous semble, vu que je ne contribue pas à songbook-web) la licence [AGPL](https://www.gnu.org/licenses/why-affero-gpl.html). Imaginons que quelqu'un fasse des modifications à songbook-web et propose ce service sur le web.
- Si songbook-web est publié sous licence GNU GPL (quelle que soit sa version), il n'est pas obligé de diffuser ses modifications, puisque le logiciel n'est pas publié (le code reste, et est exécuté, chez lui) ;
- si songbook-web est publié sous licence AGPL, alors il a l'obligation de publier également ses modifications.
