### ISSUE TITLE
Changement de l'interface de songbook-core

### ISSUE THREAD

**Issue by paternal** [patacrep/patanet#49]
Changement dans les fonctions de songbook-core qui vont affecter songbook-web : 
- la fonction [`buildsongbook()`](https://github.com/patacrep/songbook-core/blob/cd0d0ae0a54cda1c6fc56c2db5f0a243497d263d/songbook_core/build.py#L151) a été [remplacée par une classe](/patacrep/songbook-core/commit/c70fc1e7bc8e7b88da255823d50699b4e4ae0197) ;
- cette classe ne prend plus en argument le logger à utiliser : autant utiliser les fonctionnalités du module [logging](http://docs.python.org/2/library/logging.html) qui permettent de gérer les loggers d'autres modules très bien.

Pour voir la nouvelle classe en action, voyez dans le fichier [songbook](https://github.com/patacrep/songbook-core/blob/next/songbook#L117).

**Comment by Luthaf** [comment]
Résolu par b5df3e3eb4263c03e1e5d15810ff0c489b375a6a
