### ISSUE TITLE
Choix d'un schéma d'URL

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#5]
Concernant l'arborescence du site, je n'ai pas tout à fait les idées claires ...
Je partait sur quelque chose comme ça : 

```
/ -> Une page d'accueil
/admin/ -> toute la zone d'administration
/user/ -> récap. du profil, carnets de chants, etc.
    login
    logout
    change-password
    reset-password
    songbooks/ -> liste des carnets de chants
/songs/ -> Liste des artistes
    <artist>/ -> Liste des chants d'un artiste
         <song_title> -> affichage du chant
about/ -> À propos, etc.
```

Qu'est-ce que j'oublie, que je range mal, autre ?

**Comment by oliverpool** [comment]
Je mettre plutôt songbooks à la racine
avec : 
/songbooks  -> recueils publics (et persos ?)
/songbooks/my -> recueils persos
/songbooks/<songbook_slug>

**Comment by Luthaf** [comment]
Ok. Le schéma actuel est donc : 

```
/ -> Une page d'accueil
/admin/ -> toute la zone d'administration
/user/ -> récap. du profil, carnets de chants, etc.
    login
    logout
    change-password
    reset-password
    edit -> Changement du profil
/songs/ -> Liste des artistes
    <artist>/ -> Liste des chants d'un artiste
         <song_title> -> affichage du chant
/songs-list/ -> Liste alphabétique des chants
/songbooks/ -> liste des carnets de chants perso (si connecté) et publics
      <user_id>/ -> Liste des carnets de 'user'. 0 est réservé pour les carnets d'origine
            <songbook-title>/ -> Affichage de la liste des chants et récap des options du carnet
                  edit -> Modification des options
                  songs -> Modification des chants
            new/ -> Création d'un nouveau carnet
about/ -> À propos, etc.
```

Toutes ces URLs étant préfixées par la sélection de la langue : /en/songs, /fr/songs, ...
/ est équivalent à /fr/ ou /en/ suivant la langue locale ou enregistrée dans les cookies.

**Comment by jmclem** [comment]
Je verrais plutôt "artists" que "songs", c'est plus "ReST":

```
/artists -> liste des artists
/artists/tino-rossi -> infos Tino Rossi et liste des chants, pointant sur /songs/nom-du-chant
/songs -> liste des chants
/songs/petit-papa-noel -> infos "Petit Papa Noel"
/songbooks -> liste des songbooks visibles par le client (fonction de l'identité)
```

Y-a-t-il besoin du "username" dans l'URL des songbooks ? Est-ce-que

```
/songbooks/songbook-id -> le songbook "id"
```

ne suffit-il pas ?

**Comment by Luthaf** [comment]
```
/songs/petit-papa-noel -> infos "Petit Papa Noel"
```

peut ne pas fonctionner si deux artistes ont fait des chants de même nom. Sauf à forcer l'unicité du slug en ajoutant des -2 -3 -4 à la fin.

```
/songbooks/songbook-id -> le songbook "id"
```

Peut suffir en effet. J'ai bien l'idée d'avoir le titre du carnet dans l'URL, c'est plus lisible.

**Comment by jmclem** [comment]
Pour les chants, je pencherais pour l'ajout d'un id différentiateur. 

Il en faudra aussi un pour les recueils, je suppose.

 Théoriquement aussi pour les artistes, il y a bien quelques groupes/auteurs qui ont le même nom, non ? Est-ce qu'on force à avoir des noms différents? (`Artist.name` serait unique)

**Comment by oliverpool** [comment]
concernant

```
/songs/ -> Liste des artistes
    <artist>/ -> Liste des chants d'un artiste
         <song_title> -> affichage du chant
/songs-list/ -> Liste alphabétique des chants
```

je propose

```
/songs/ -> Liste des chansons de tous les artistes (alphabétique par chanson)
    <artist>/ -> Liste des chants d'un artiste
         <song_title> -> affichage du chant
/artists/ -> Liste alphabétique des artistes
```

pour les artistes qui ont le même nom, comment se comporte patacrep ?
(idéalement, il faudrait que <artist>/<song_title>.sg corresponde entre les deux :-)

**Comment by Luthaf** [comment]
Pourquoi pas ajouter un id pour les chants et les receuils, c'est plus simple et on peut toujours avoir le slug dans l'URL. J'en arrive donc à ça : 

```
/ -> Une page d'accueil
/admin/ -> toute la zone d'administration

/user/ -> récap. du profil, carnets de chants, etc.
    login
    logout
    change-password
    reset-password
    edit -> Changement du profil

/songs/ -> Liste des chansons de tous les artistes (alphabétique par chanson)
    random -> Chant au hasard
    search?<termes de recherche>
    <artist>/ -> Liste des chants d'un artiste
        <id> - <song_title>/ -> affichage du chant
                edit -> tout est dit ^^
                history
/artists/ -> Liste alphabétique des artistes

/songbooks/ -> liste des carnets de chants perso (si connecté) et publics
      <id> - <songbook-title>/ -> liste des chants et des options du carnet
                  edit -> Modification des options
                  songs -> Modification des chants
            new -> Création d'un nouveau carnet

contribute/ -> Règles de base pour l'écriture des chants
        help -> Ensemble de la syntaxe

about/ -> À propos

contact/
```

Je pense que l'on arrive à quelque chose de pas mal, non ? Il manque quelques pages statiques, mais pas grand chose d'autre pour moi. Vous en pensez quoi ?

Il faut que je vois pour l'unicité des noms d'artiste comment fait le système de compilation. Je ne crois pas que ce cas soit géré.

**Comment by Luthaf** [comment]
> Je ne crois pas que ce cas soit géré.

En effet, ce n'est pas géré. Avant de fermer, je propose juste une petite modification pour le rendu des carnets : utiliser aussi une URL de type `/fr/songbooks/<id>-<slug>/render`

**Comment by jmclem** [comment]
> utiliser aussi une URL de type /fr/songbooks/<id>-<slug>/render

C'est marrant, j'avais commencé avec, puis j'en suis revenu en me disant que la redondance n'était pas nécessaire; ce n'est pas vraiment une url "vue par l'utilisateur"

**Comment by Luthaf** [comment]
En effet. Mais tant au,a faire, je préfère un schéma unifié
