### ISSUE TITLE
Modifier les fichiers LaTeX depuis l'interface web

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#50]
Il est prévu que l'utilisateur puisse ajouter ses propres chansons, ou corriger des chansons existantes depuis l'interface web. Seulement, (La)TeX est un langage Turing complet (oui, oui !) qui permet des attaques sur n'importe quel système. Par exemple, [ce papier](https://www.usenix.org/legacy/events/leet10/tech/full_papers/Checkoway.pdf) explique comment créer un virus sous Windows avec LaTeX, et comment récupérer des informations diverses (lire \etc\passwd par exemple) sous UNIX.

Bref, le risque de sécurité en permettant à l'utilisateur d’exécuter du code arbitraire sur le serveur est important. Une première chose à faire est de désactiver l'option `--shell-escape` lors de la compilation, pour empêcher d'utiliser des commandes système (Je crois. Je ne connais pas le comportement exact de cette option).

Une seconde chose à faire est de filtrer les commandes envoyées à la compilation, c'est-à-dire le contenu du texte entré par les utilisateurs (empécher toute utilisation de `\catcode`, de `\write`...). Pour ce faire, je vois deux possibilités principales : 
- Vérifier à coup de regex que le texte entré ne contient pas certaines commandes, ou mieux, qu'il ne contient que les commandes autorisées (`\begin{verse}`, `\image`, ...)
- Mieux encore, utiliser un langage intermédiaire, comme le langage [chordpro](www.vromans.org/johan/projects/Chordii/chordpro/index.html), et effectuer nous-même la traduction. 

La seconde possibilité à ma préférence, mais elle demande plus de travail. Il faut aussi se demander si elle doit être inclue dans songbook-web ou dans songbook-core.

**Comment by oliverpool** [comment]
J'ai une préférence personnelle pour la première possibilité: seulement certaines commandes sont utilisées (mais sans aucun fondement...)

---

Implémentation très peu subtile :
- on a un tableau avec les commandes autorisées
- lorsqu'on a un input utilisateur, on échappe toutes les commandes LaTeX
- on fait un remplacement de chaines de caractères pour chacun des élements du tableau :
  - chaine à remplacer : item du tableau, lui-même échappé (avec la même fonction que précédemment)
  - chaine de remplacement : item d'origine du tableau

**Comment by paternal** [comment]
> Vérifier à coup de regex que le texte entré ne contient pas certaines commandes, ou mieux, qu'il ne contient que les commandes autorisées (\begin{verse}, \image, ...)

Le [papier](https://www.usenix.org/legacy/events/leet10/tech/full_papers/Checkoway.pdf) dont tu donnes le lien explique justement les limitations d'une approche par liste noire (interdire certaines commandes) : c'est en partie 4.5.
La seconde approche que tu proposes, par liste blanche, me semble déjà plus acceptable, mais je ne l'utiliserais pas avant d'avoir la certitude que c'est correct.

Finalement, je pense que la meilleure manière de traiter ce risque est d'exécuter songbook-web dans un environnement chrooté (conseillé en 4.8), en l'exécutant avec un utilisateur particulier (voir la fonctionnalité [suEXEC](https://httpd.apache.org/docs/trunk/fr/suexec.html)).

Je viens d'errer un peu sur la toile pour regarder comment vous pouvez faire, et… bonne chance !

**Comment by Luthaf** [comment]
Je pense qu'une liste blanche qui ne contienne que 

``` LaTeX
\beginsong
\endsong
\beginverse
\endverse
\beginchorus
\endchorus

\musicnote
\textnote

\image

\cover

\gtab
\utab

\[...]
```

et qui échappe tous les autres caractères spéciaux LaTeX (`$ & % # { } _ \ ^ ~`) devrait être suffisante. Dans le papier en question, l'approche liste blanche n'est pas conseillée pour des visualiseur LaTeX, qui doivent autorise beaucoup de commandes pour être utiles. Mais avec cette liste, il est impossible de changer de catcode ou d'ajouter une commande avec `\csname`. Ai-je oublie des commandes utiles ?

On peut aussi ajouter (dans songbook-core ?) une protection DDOS en limitant la durée d'une compilation. Ca éviterai un blocage de la liste des compilation par une compilation foireuse. TeX se bloque tout seul en terme de mémoire, il faut que je vérifie les valeurs.

> Finalement, je pense que la meilleure manière de traiter ce risque est d'exécuter songbook-web dans un environnement chrooté (conseillé en 4.8), en l'exécutant avec un utilisateur particulier (voir la fonctionnalité suEXEC).

Ca serait pas mal aussi. Normalement, il n'y a pas besoin de suEXEC, vu la compilation est gérée directement avec un processus Python en parallèle.

**Comment by Luthaf** [comment]
D'un point de vue interface, il y a ça qui existe déjà : 
http://www.carnet-de-chants.fr/ajout-de-chansons/new.html

L'idée est de découper la chanson en un ensemble de `textarea` correspondant à chaque part d'une chanson (couplet, refrain), et de ne permettre à l'utilisateur l'utilisation que de [] pour entrer les accords. Le fichier .sb est ensuite créé par le code Python. Tous les caractères spéciaux TeX sont soit échappés (%, ~, ^) soit supprimés (`\`).

Il faut donc écrire un ensemble de fonctions fichier sb <-> formulaire qui gère ça.
Parmi les différents types d'entrées, il y a à prévoir : 

```
chorus
verse
verse*
bridge
textnote
musicnote
```

**Comment by Luthaf** [comment]
> L'idée est de découper la chanson en un ensemble de textarea correspondant à chaque part d'une chanson (couplet, refrain), et de ne permettre à l'utilisateur l'utilisation que de [] pour entrer les accords. Le fichier .sb est ensuite créé par le code Python. Tous les caractères spéciaux TeX sont soit échappés (%, ~, ^) soit supprimés ().

Une manière de l’implémenter avec jQuery : http://www.sanwebe.com/2013/03/addremove-input-fields-dynamically-with-jquery/comment-page-1

Par contre on perd totalement le support des navigateurs sans JS pour l'ajout des chants. Des avis la dessus ?

Pour la mise a jour des chants, on peut utiliser des [formset](https://docs.djangoproject.com/en/1.7/topics/forms/formsets/) pré-remplis avec le contenu des chansons séparé en plusieurs parties.

**Comment by paternal** [comment]
> Par contre on perd totalement le support des navigateurs sans JS pour l'ajout des chants. Des avis la dessus ?

Laisser un bête champs de texte brut s'il n'y a pas de JS, le remplacer par ce que tu proposes si JS est disponible ?

De toutes manières, il y aura sûrement un aperçu du rendu, qui permettra de ne pas avancer à l'aveugle, même avec du texte brut, non ?

**Comment by oliverpool** [comment]
> Laisser un bête champs de texte brut s'il n'y a pas de JS, le remplacer par ce que tu proposes si JS est disponible ?

La vraie question, est que doit traiter la requête POST qui reçoit tout ça:
- un ensemble de textarea (un par couplet/refrain/bridge...)
- un seul texteara avec les commandes begin/end (automatiquement mises par JS si supporté par le navigateur)

**Comment by Luthaf** [comment]
> Laisser un bête champs de texte brut s'il n'y a pas de JS, le remplacer par ce que tu proposes si JS est disponible 

Sans doutes le plus simple en effet, mais du coup cela ajoute une possibilité de faille de sécurité : il faut vérifier que toutes les commandes LaTeX rentrées sont autorisées. L'idee de l'interface est de generer le .sg en ajoutant depuis Python toutes les commandes `

> De toutes manières, il y aura sûrement un aperçu du rendu, qui permettra de ne pas avancer à l'aveugle, même avec du texte brut, non ?

Pas forcement, avec cette interface l'utilisateur n'a besoin d'entrer que du texte et le placement des accords. Une entrée utilisateur ressemblerai simplement a : 

```
J'[C]ai traî[G]né dans [F]tous les caf[C]és
J'ai fait la [G7]manche bien des [C]soirs
Les [C]temps sont [G]durs
J'suis [F]même pas [C]sûr
[C]De me payer [G7]un coup à [C]boire
```

avec un champ par "bout" de chanson (refrain, couplet, ...)

Mais cela pourrait être intéressant a implémenter pour une 0.3.

> La vraie question, est que doit traiter la requête POST qui reçoit tout ça:

On peut ajouter un champ caché, modifié par JS qui permette de faire la différence. Si on veut éviter de faire 2 traitement, on peut simplement ajouter un pré-traitement dans le cas de plusieurs textarea, juste pour les assembler.

**Comment by Luthaf** [comment]
En lien avec ce problème, une possibilité pour créer des locks de fichiers en python : https://pypi.python.org/pypi/lockfile

**Comment by oliverpool** [comment]
Je pense qu'on peut fermer cette issue et en ouvrir une nouvelle "Modifier les chants" dès qu'on aura basculé sur le format chordpro (où les problèmes de sécurités sont normalement absents).

**Comment by Luthaf** [comment]
On garde les problèmes de lock des fichiers, même avec Chordpro. Sinon je suis d'accord =)
