### ISSUE TITLE
Implémenter une recherche parmi les chants

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#52]
Juste une issue parce qu'il faudra bien le faire un jour =)

**Comment by oliverpool** [comment]
une recherche dans les titre + artistes ne doit pas être trop complexe et déjà assez satisfaisante (à voir comment on gère les accents...)

Pour les recherches dans les paroles, peut-être qu'on peut s'en remettre aux moteurs de recherches traditionnels

**Comment by Luthaf** [comment]
Il y a des solutions clefs en main qui valent le coup je pense. Par exemple [haystask](http://blog.providenz.fr/2010/03/haystack-la-recherche-avec-django/).

**Comment by Soundy25** [comment]
Qui dit moteur de recherche dit (aujourdhui) ... autocomplétion ! 
J'imagine que si le service propose une recherche libre et une option de filtre sur : artiste, titre et contenus ce serait déjà pas mal.

Après si on se met à la place de l'utilisateur, pourquoi pas proposer une recherche par accords, comme ça un débutant trouverait rapidement une sélection de chants basés sur les accord qu'il maitrise et progresser grace à ça.

**Comment by oliverpool** [comment]
que de bonnes idées ! (mais ça risque d'attendre une version 0.4, 0.5 voire plus ^^)

**Comment by Luthaf** [comment]
Passage eclair : pour l'autocompletion, il y a un module Django : https://github.com/yourlabs/django-autocomplete-light

**Comment by oliverpool** [comment]
Recherche dans les titre + artistes implémentée.

Pour la gestion des accents, j'ai rusé : la recherche est se fait parmi les titre et le slug ! (donc si l'utilisateur ne met pas d'accents la recherche est "large")

**Comment by oliverpool** [comment]
Cf PR #116

Pour d'autre fonctionnalités (auto-complétion, recherche parmi le texte) on pourra ouvrir des issues en temps voulu
