### ISSUE TITLE
Compiler les fichiers LESS

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#53]
L'utilisation traditionelle des fichiers .less est de les compiler en .css avec Node.js. Toutefois dans notre cas, ce n'est pas forcement adapté. Mais la compilation et le maintient dans git des fichiers .css rajoute pas mal de commits inutiles lors des modifications de design.

Pourquoi ne pas rajouter une commande à manage.py qui se charge de compiler ces fichiers lors de l'installation ? Ça serait réalisable avec [lesscpy](https://pypi.python.org/pypi/lesscpy) par exemple. Toutes les fonctionnalités utilisées actuellement sont supportées. Qu'en pensez-vous ?

**Comment by jmclem** [comment]
Il y a aussi ça : https://github.com/andreyfedoseev/django-static-precompiler

**Comment by Luthaf** [comment]
Le problème de static-precompiler, c'est qu'il faut installer par ailleurs un compilateur less, et donc sans doutes nodes.js. Après, on peut utiliser lesscpy comme compilateur avec static-precompiler. Mais j'aime bien l’idée de ne compiler que lors du `colectstatic`

**Comment by oliverpool** [comment]
ça me convient

Il suffit de "l'accrocher" pour qu'il soit appelé lors d'un push, non ? (et en local on garde le less.js)

**Comment by Luthaf** [comment]
> Il suffit de "l'accrocher" pour qu'il soit appelé lors d'un push, non ? (et en local on garde le less.js)

En local on garde less.js en effet. Que veux-tu dire par "l'accrocher" ?

Sinon, c'est fait (a7ff3fa5ae95e9f17d6a51a259471e7694ccdf0a).

Avant de passer sur le serveur il va falloir installer lesscpy (@jmclem, c'est pour toi ^^, je vais mettre a jour le script de pull pour qu'il effectue le `collectstatic`)

@oliverpool  : le compilateur n'est pas parfait, et renvoyait quelques erreurs de syntaxe avec les fichiers LESS. Je les ai modifiés (70b82deed50f11c0b57a17c924ae5831879a0881), mais j'ai du supprimer le "." après les numéros verses dans songs.less.

**Comment by jmclem** [comment]
> il va falloir installer lesscpy

C'est fait : 

```
:~$ lessc -v
lessc 1.7.0 (LESS Compiler) [JavaScript]
```

**Comment by Luthaf** [comment]
Arf, je n'ai pas été clair ... En fait, il n'y a pas du tout besoin de node.js ou de `lessc`. Tout est géré en Python, et il y a un package `lesscpy`, que l'on peut installer avec pip. Je trouvais cela plus simple pour gérer l'installation.

**Comment by jmclem** [comment]
OK, c'est fait aussi ;)

**Comment by Luthaf** [comment]
Cool =)

Je vais me mettre à la doc ce we, ça devient urgent (que ce soit pour songbook-core ou pour songbook-web). C'est assez clair dans ma tête, mais ce n'est pas suffisant ^^

**Comment by oliverpool** [comment]
@Luthaf : comment est-ce que la compilation less vers css est déclenchée ?
Avec Git, il y a moyen de mettre des [Hooks](http://git-scm.com/book/en/Customizing-Git-Git-Hooks) pour exécuter une commande (compilation less vers css) lors de la mise à jour du répertoire.

**Comment by Luthaf** [comment]
Pour le moment, la mise en place sur le serveur est faite manuellement : il faut faire un `git pull`. Puis les fichiers statiques sont rasemblés dans un dossier pour qu'Apache s'en charge. C'est à la fin de cette étape de rassemblage (commande `collectstatic`) des fichiers que la compilation a lieu.

EDIT : Du coup, je ferme, ce problème est résolu.
