### ISSUE TITLE
Echapper les entrées utilisateur

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#54]
Pour l'instant, les valeurs entrées par l'utilisateur (title, description, ...) ne sont pas échappée pour tenir compte des commandes LaTeX, il est donc possible d'insérer du code. Il faut donc ajouter un phase de validation/nettoyage à ces entrée, étant donné qu'elles sont envoyées à pdflatex ensuite.

Seules les commandes LaTeX ont besoin d'être échappées, le code HTML l'est déjà. En pratique, je pense que l'on peut violemment supprimer tous les `\` présent dans ces champs (avec au besoin un warning).

**Comment by paternal** [comment]
En quoi est-ce un problème si le document est compilé sans l'option `--shell-escape` ?

**Comment by Luthaf** [comment]
Cela peut faire planter la compilation LaTeX du carnet. Ce n'est pas forcément un problème de sécurité, mais l'utilisateur de voit que "La compilation a échouée" et pas le log. Donc pour éviter des problèmes, autant supprimer les caractère spéciaux LaTeX.

**Comment by Luthaf** [comment]
Fait (eeab174ae615749ed5b9c0c426e21166d5bc8524)
