### ISSUE TITLE
"Langue" des accords

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#56]
Je viens de générer un carnet (http://songbook-web.tk/medias/PDF/songbook-9.pdf), et les accords ne sont pas cohérents:
- page 4, à gauche il y a écrit "Do", alors qu'il y a un "C" au dessus des tablatures
- page 9, chanson "Against The Wind", les commentaires sont en Francais et en Anglais

PS : cela est peut-être un bug de songbook-core ?

**Comment by Luthaf** [comment]
Ce sont en effet des problemes de songbook-core. 

Le premier est lie au package [chords](https://github.com/patacrep/songbook-core/blob/next/songbook_core/data/latex/chords.sty#L64) ou les noms d'accords sont écrits en durs. Ca doit être assez simple a corriger.

Le second je ne sais pas, j'ai modifie les commandes correspondantes dans [cette pull-request](https://github.com/patacrep/songbook-core/pull/32), donc il faudra revérifier après la fusion.

EDIT: Au passage, il faudrait ajouter la commande de traduction des accords en francais si le carnet est en francais, histoire d’être cohérent.

**Comment by oliverpool** [comment]
En fait `\chordnameC` doit vérifier la langue courante avant d'afficher le nom,
alors que `\gtab{C}` doit être traduit 'à postério' par les commandes _qui vont bien_.
(la pull-request le corrigera peut-être)

**Comment by Luthaf** [comment]
Il faudrait voir si il est possible d'utiliser le changement automatique de nom du package song http://songs.sourceforge.net/songsdoc/songs.html#sec7.0.4 pour faire ces modifications de langues.

**Comment by Luthaf** [comment]
Corrigé dans songbook-core : https://github.com/patacrep/songbook-core/pull/35
