### ISSUE TITLE
Ajout et suppression de chansons à corriger

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#57]
Un premier retour de bugs : 
- Il est possible d'ajouter deux fois l'ensemble des chansons d'un artiste.
- Il est impossible de supprimer un chant depuis la page des paroles. 

Le premier bug est du au fait que l'on a pas encore de moyen de verifier si tous les chants d'un artiste sont dans la liste des chants. Le second correspond à un TODO ...

**Comment by oliverpool** [comment]
Le premier : il suffirait de vérifier à chaque ajout d'une chanson, que celle-ci n'est pas déjà dans le recueil (ex : j'ai ajouté 2 chansons d'un artiste, et finalement je veux toutes les chansons de cet artiste)

On peut faire une `key` unique avec `id_song*id_recueil` ?

**Comment by Luthaf** [comment]
> Le premier : il suffirait de vérifier à chaque ajout d'une chanson, que celle-ci n'est pas déjà dans le recueil (ex : j'ai ajouté 2 chansons d'un artiste, et finalement je veux toutes les chansons de cet artiste)

C'était déjà le cas en fait, mais le passage de SongInSongbook à ItemsInSongbook a tout cassé.

Corrigé par les commits : 
300a6170eac5c341f972fe77cab3046b7641a6fc
f82f871a8b0d6d1ccd769ee3432fb0fe9c3cc830
9192969e3655749f65c7f27a1e2d2ea7d78462d7
