### ISSUE TITLE
Accès aux fichiers PDFs

### ISSUE THREAD

**Issue by jmclem** [patacrep/patanet#58]
Aujourd'hui, sur la version beta, n'importe qui peut télécharger un carnet dont il connait le nom (qui ne sont aujourd'hui pas difficiles à deviner ;) ).

Pour permettre le respect des carnets privés, je vois deux solutions : 
- mettre en place une authentification
- stocker les PDFs dans des sous-répertoires 'cryptiques' qui évitent qu'ils puissent être devinés

Je préfère nettement la deuxième, qui permet en outre de partager un carnet facilement.

**Comment by Luthaf** [comment]
Je suis pour la seconde aussi. Je pense qu'il suffit de modifier la fonction [build](https://github.com/patacrep/songbook-web/blob/master/generator/build.py#L62) pour qu'elle utilise et renvoie un nom cryptique.

On peut soit stocker un nom de dossier temporaire en BDD, soit utiliser le hash du carnet.

**Comment by Luthaf** [comment]
Une proposition d'un beta-testeur : ouvrir les liens des carnets dans un nouvel onglet/une nouvelle fenêtre.

**Comment by oliverpool** [comment]
"les liens des carnets" : tu fais référence aux liens vers les fichiers pdf ? 
Si oui je suis ok (pour rajouter le `target="_blank"` aux tags `<a>`)

**Comment by Luthaf** [comment]
Oui, c'est cela.
