### ISSUE TITLE
Sample settings & importsongs

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#60]
J'ai profité de mon absence prolongée pour faire une installation neuve du projet !

J'ai légèrement accroché lors de `importsongs`:
- settings.SONG_PROCESSOR_DIR du fichier sample (https://github.com/patacrep/songbook-web/blob/master/Songbook_web/local_settings.sample.py#L64) n'est pas défini...
- et https://github.com/patacrep/songbook-web/blob/master/generator/management/commands/importsongs.py#L26 cherche u sous-dossier "songs", alors que songbook-data n'en a pas...

Du coup si vous êtes d'accord, j'ai un commit pour remplacer SONGS_DIR par settings.SONGS_LIBRARY_DIR de partout

**Comment by Luthaf** [comment]
> et https://github.com/patacrep/songbook-web/blob/master/generator/management/commands/importsongs.py#L26 cherche u sous-dossier "songs", alors que songbook-data n'en a pas...

Si, dans la branche next. Il faut utiliser les branches next de songbook-core et songbook-data pour le moment. 

`SONG_PROCESSOR_DIR` ne sert en effet plus, il ne faut mettre que `SONGS_LIBRARY_DIR`qui pointe vers songbook-data.

Il va vraiment falloir mettre à jour la doc (#55)

**Comment by oliverpool** [comment]
Ok, j'avais effectivement oublié de changer de branche sur songbook-data...
