### ISSUE TITLE
Design : liste des carnets

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#61]
Je vais essayer de prendre le temps de mener la refonte du design jusqu'au bout...

Voici donc une première étape : le désign des listes des carnets (publics/privés).

Ci-dessous une proposition:
![proposition](https://cloud.githubusercontent.com/assets/3864879/2985899/adf0f542-dc3f-11e3-9330-37dfb685e3b2.png)
Tout ce qui est en vert souligné est un lien:
- Editer la description permet d'éditer le titre, le sous-titre et le public/privé.
- Public/Privé est aussi un lien vers cette page (seulement vert souligné au survol uniquement)
- Le lien Téléchargement renvoie vers une page où l'on peut regénérer les différentes mises en page
- Un utilisateur n'ayant pas les droits sur un carnet ne verra pas les 4 liens du bas (et téléchargements ne sera plus un lien)

---

Qu'en pensez-vous ?

_Je préfères avoir des avis/suggestions/critiques sur un png avant de me lancer dans le CSS ;-)_

**Comment by Luthaf** [comment]
Alors d'un point de vue design, j'aime bien. Le vert en couleur de fond est juste un peu trop saturé, je trouve que le texte est moins lisible. De manière générale, pourquoi ne pas utiliser un peu plus de couleurs ? Gris, bleu, jaune, ...

D'un point de vue organisation, je ne sais pas trop comment organiser la section Téléchargements.

Je verrais bien quelque chose comme 

```
Téléchargements
    - Paroles uniquement
    - Paroles et accords
    - Ma mise en page <- Un ou deux liens des derniers Layout utilises.
    - ... Voir toutes les versions de ce carnet
```

Le lien "Téléchargement" et "voir toutes les versions de ce carnet" renvoyant vers la même vue : une liste des Layouts utilisées par cet utilisateur avec descriptif des options, plus un formulaire pour créer une nouvelle mise en page. Les versions "avec accords" et "sans accord" de base étant toujours disponibles.

A cote de cette liste des Layouts, les liens de téléchargement pour chaque Layout qui a été généré. Sur la liste des carnets, les liens "Paroles uniquement" sont soit des liens qui lancent la génération, soit des liens de téléchargement. On peut utiliser l'espace a droite pour afficher des infos sur l’état actuelle de la compilation.

D'un point de vue plus technique, je pense qu'il serait bien d'avoir une requête POST pour lancer les compilations, donc plutôt un formulaire (avec comme champs `songbook_id`, `layout_id` et `force`) qu'un lien.

PS : je préfère largement tes propositions de design aux miennes !

**Comment by oliverpool** [comment]
merci pour les remarques:
J'ai choisi les couleurs rapidement : clairement il faudra les changer (mais c'est rapide à faire à postériori)

Pour la section téléchargement, on peut faire deux comportements différents:
- si ce n'est pas mon carnet
  - "Téléchargement" renvoie vers la liste des "Layouts" disponibles au téléchargement
  - chaque élément renvoie directement vers le pdf (si le pdf n'existe pas, on masque l'élément)
- si c'est mon carnet:
  - "Téléchargement" renvoie vers la vue que tu propose
  - chaque éléments renvoie vers des vues qui permettent d'éditer les options et de régénéré un carnet

J'imagine pas trop de cas avec plein de mise en page différentes, et donc je propose d'afficher toutes les mises en page systématiquement (si il s'avère que beaucoup de carnets ont plein de mises en page, on corrigera)

C'est noté pour la compilation. Je suis même partisan de "forcer" une vue intermédiaire (contenant donc ton formulaire) avant la compilation (notamment pour afficher si une compilation est en cours, ou des messages d'erreur)

**Comment by Luthaf** [comment]
Fait dans une version minimaliste. Issue à réouvrir quand on aura plus de temps à passer sur le Design.
