### ISSUE TITLE
Design : ajout des chants au carnet

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#62]
A l'usage, je me dis qu'afficher la liste actuelle des chants sur chacune des pages (artistes, chants, liste des artistes...) n'est pas très pertinent (et prend beaucoup de place).

Je propose donc un changement radical.
Dans l'idée, on affiche un encart juste avant le titre h1 (titre de chanson, nom de l'artiste...). Par exemple en éditant rapidement [Wikipédia](http://fr.wikipedia.org/wiki/Sp%C3%A9cial:Livre), ça donne cela:
![top-bar](https://cloud.githubusercontent.com/assets/3864879/2986190/308ed7ce-dc42-11e3-9c42-534b8f5a1049.png)

_Retirer ce chant du carnet_ sera dynamiquement adapté (Retirer/Ajouter, chant/artiste)
_Changer de carnet_ renvoie vers la page des carnets privés

Si l'utilisateur n'a pas de carnet sélectionner, on peut lui proposer les deux options (comme actuellement):
- enrichir un carnet existant
- créer un nouveau carnet

---

Qu'en pensez-vous ?

**Comment by Luthaf** [comment]
En effet, la liste a droite prend beaucoup de place. Cette idée est plutôt bien, je me demande juste si elle est totalement adaptée aux listes de chansons/artistes. Dans ce cas, je supprimerai bien le "Ajouter/Retirer du carnet" pour mettre un bouton global "ajouter les chants/artistes sélectionnés au carnet". 

A voir avec l'utilisation d'AJAX en parallèle pour l'ajout/suppression de chants.

**Comment by oliverpool** [comment]
C'est pas faux.
Le bouton "Ajouter la selection" aurait peut être plus sa place en bas de liste (c'est plus naturel pour la lecture) et le lien que je propose pourrait être transformé en "Ajouter tous les artistes/toutes les chansons".
(mais le top du top pour les sélection, c'est l'AJAX ;-)

**Comment by Luthaf** [comment]
Voir en haut et en bas de la liste, pour ne pas trop avoir a scroller.

**Comment by oliverpool** [comment]
En effet
(même si je pense que si tu fais une sélection tu va scroller jusqu'au bout de la liste)

**Comment by Luthaf** [comment]
Fait dans une version minimaliste. Issue à réouvrir quand on aura plus de temps à passer sur le Design.

**Comment by oliverpool** [comment]
Ca y est: je m'y suis mis !
Dans un nouvelle branche : test_design

**Comment by Luthaf** [comment]
Cool ! 

(Fait gaffe, tu as fait tous les commits avec une autre identité git)

**Comment by oliverpool** [comment]
J'ai corrigé l'identité git en basculant sur une autre branche : test_design. 
(certe, il reste un commit qui se balade, mais le supprimer risque de causer plus d'ennuis qu'autre chose...)

J'ai fait pas mal de modifications aujourd'hui:
- quelques retouches de formulaire
- gros effort sur l'unification des pages reliées à un carnet
  (en lien avec #61 et #67)

Qu'en pensez-vous ?

PS: chez moi la ligne 7 de full_layout `{% if debug %}` est toujours à False, bien que dans localsettings, il y ait :
DEBUG = True
TEMPLATE_DEBUG = True

**Comment by Luthaf** [comment]
> J'ai fait pas mal de modifications aujourd'hui:

34 commits, pas mal ^^

Je regarde, et je reviens par ici.
