### ISSUE TITLE
Translate the interface in english

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#64]
Someone just proposed his help to translate the website in English, so I open this issue to discuss about this.

A short reminder about how translation works with Django : 
- Create or update messages files (.po) with `django-admin.py makemessages -l en`
- Compile messages to gettext optimized binary files (.mo) with `django-admin.py compilemessages`

And the documentation is [here](https://docs.djangoproject.com/en/dev/topics/i18n/translation/).

**Comment by jjlwork** [comment]
Je suis hereus de vous aidez! Initial translations are complete. Hopefully I did everything correctly.

**Comment by Luthaf** [comment]
Good and very fast work ! I added some comments to your commit : https://github.com/patacrep/songbook-web/commit/99f52a58ea06859c8a4548645605841bdd9f879c

**Comment by jjlwork** [comment]
Thanks. I fixed all of the issues except the 80 character limit. I think
this may be a limitation of Poedit. In my research there were a few
complaints about Poedit with respect to this issue and no fixes that I
could find. In addition I am not sure what the "80 character limit" refers
to or how to fix by hand using an editor. Also, I am unable to compile the
.po file to .mo on the command line suing the command you provided
"django-admin.py
compilemessages" , the .mo file included was generated was created by
poedit.

**Comment by Luthaf** [comment]
When you run `django-admin.py compilemessages`, what is the output ?

**Comment by jjlwork** [comment]
Actually I figured the compile issues out. I was trying to compile from
directory with the .po file and not from the songbook-web directory. So the
only thing left to figure out is if this 80 character limit is going to be
an issue and if so how to work around it. I will commit the new .mo file
generated via command line instead of the Poedit one generated when saved.

**Comment by jjlwork** [comment]
actually doing "git status" after running the command to create the binary
for the po file there weren't any changes. So i guess I don't need to
commit again.

**Comment by Luthaf** [comment]
The issue with the characters limit seems not to be an issue, so we can ignore it.

The beta server is now running with the translation, you can see it at the adress http://songbook-web.tk/en/

**Comment by jjlwork** [comment]
Excellent, looks good to me, but I did see a couple of things I might need to re-word a bit better.

How do I go about translating the Home page? 

I noticed when I create a songbook the date, table of contents, authors are all in french. I am thinking that this may be something that will come in the future when it is possible to edit the template?

I also noticed the navigation headings are still in french when browsing the English version.

**Comment by Luthaf** [comment]
> How do I go about translating the Home page? 

The current home page is only for the beta, so I do not think it is worth translating it now.

> I noticed when I create a songbook the date, table of contents, authors are all in french. I am thinking that this may be something that will come in the future when it is possible to edit the template?

Effectively ! The main language should be added as option to the Layout, or to the Songbook, either basing on the current user main language or giving the user a choice. @jmclem, your opinion about it ?
Songbook-core can already translate everything in english, with the `lang` option.

**Comment by jjlwork** [comment]
Defaulting to the user locale but still offering the choice of build language would be ideal to me.

**Comment by oliverpool** [comment]
Thank you very much for doing the translation !

**Comment by Luthaf** [comment]
I close this issue, but there will still be some translations to do when the website is updated
