### ISSUE TITLE
When you add a song to an already generated songbook, let the user know that PDF version is not current.

### ISSUE THREAD

**Issue by jjlwork** [patacrep/patanet#65]
I noticed when I add a song to a songbook that has already been generated and go back to "my songbooks" it states "The songbook is ready". I am thinking this should change to "The songbook has changed since last generated".

**Comment by Luthaf** [comment]
Effectively. This could easily be done by comparing `songbook.hash` and `task.hash`.

**Comment by jmclem** [comment]
OK, I propose I cover this when I go on with #36 and #61
