### ISSUE TITLE
Development wiki - error on last step before running server?

### ISSUE THREAD

**Issue by jjlwork** [patacrep/patanet#66]
I started fresh and followed the development wiki, when running the last command before starting the server "./manage.py importsongs", i get the following error:
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    **import**(name)
  File "/home/jaxor/git/patacrep/songbook-web/generator/management/commands/importsongs.py", line 20, in <module>
    from songbook_core.plastex import parsetex
ImportError: No module named songbook_core.plastex

**Comment by jmclem** [comment]
Did you install the plastex package ? It doesn't come through pip, you'll have to install it from hand. Get it there : http://sourceforge.net/projects/plastex/files/

**Comment by Luthaf** [comment]
I add this information on the wiki.

**Comment by jjlwork** [comment]
I installed the plastex package. I still get the exact same output :(

**Comment by jjlwork** [comment]
Perhaps it has to do with the songbook-core? What does it mean to "Download and install the compilation engine" is this simply copying songbook-core to songbook-web directory?

my paths to songbook-core and songbook-web are :

/home/jaxor/git/patacrep/songbook-core
/home/jaxor/git/patacrep/songbook-web

I've tried copy the folder to songbook-web so it looks as follows:
/home/jaxor/git/patacrep/songbook-web/songbook-core

But this also gave the same error.

**Comment by jmclem** [comment]
Indeed, you're right, you'll have to install songbook-core : 

```
$ cd patacrep/songbook-core
$ sudo ./setup.py install
```

Be sure you're on the `next` branch (`git checkout next`).
The paths to core, web and data can be on the same level (e.g. all directly below patacrep).

**Comment by jjlwork** [comment]
When I git clone songbook-core there is no setup.py.

**Comment by Luthaf** [comment]
You have to checkout to the next branch. It will be merged soon !

**Comment by jjlwork** [comment]
So I didn't do it wrong it just can't be setup yet. I'll wait for the merge.

**Comment by Luthaf** [comment]
You can install it now, there is just an extra step. Just run `git checkout next` in the songbook-core directory.

**Comment by jjlwork** [comment]
Perfect.

**Comment by jjlwork** [comment]
up and running, thanks!
