### ISSUE TITLE
Parse song files in a tree and fill db with information

### ISSUE THREAD

**Issue by jmclem** [patacrep/patanet#7]

**Comment by oliverpool** [comment]
I think there is also two steps :
1. create a class SongFile to make abstraction of the *.sg files
2. recursively use the class to parse every file and fill the db

**Comment by jmclem** [comment]
Maybe, I didn't think much about it yet. 

As for parsing, I think we should check whether the plastex package (or any other package providing latex parsing) can be of any help.

**Comment by oliverpool** [comment]
Or just some brutal regexp : https://github.com/crep4ever/songbook-client/blob/master/src/song.cc#L28

edit : because we only need header info for the db (we don't need to parse the song content - at least for the beginning)

**Comment by jmclem** [comment]
RE may indeed be OK in the beginning.

**Comment by Luthaf** [comment]
In fact, their is something similar in the songbook compilator that we can reuse.

A song class exist, with a PlasTex parser and with recursive finding.

**Comment by jmclem** [comment]
Ok, je m'y attaque

**Comment by jmclem** [comment]
J'ai commencé par créer un  fixture avec quelques chants et artistes pour que les autres aspects puissent avancer. Il est possible de charger les données avec : `./manage.py loaddata few_songs.json`.

**Comment by Luthaf** [comment]
Les champs 'slug' sont utilisés comme url et donc identifiant unique des chansons/artistes. Ceux produits par Django sont de la forme "L'hypermarché bleu" -> "l-hypermarche-bleu"

Il y a une fonction slugify quelque part qui fait ça toute seule

**Comment by jmclem** [comment]
J'ai avancé un peu sur l'import; j'ai commité dans mon fork : https://github.com/jmclem/songbook-web
Voici ce que j'ai fait:
- modifié les modèles : ajout d'un modèle GitFile pour garder trace du lien git et quelques autres modifs (https://github.com/jmclem/songbook-web/commit/da250f6d56cebab9918f10d6e45d72f21389d904#diff-7)
- ajout d'une variable SONG_PROCESSOR_LIBRARY pointant sur les outils patacrep de la repo songbook (https://github.com/jmclem/songbook-web/commit/da250f6d56cebab9918f10d6e45d72f21389d904#diff-0)
- création d'une commande importsongs (pour pouvoir faire `./manage.py importsongs`) : https://github.com/jmclem/songbook-web/blob/da250f6d56cebab9918f10d6e45d72f21389d904/generator/management/commands/importsongs.py

Pour l'instant, ça lit les chants, crée les modèles, mais c'est pas tout à fait fini.

J'utilise le parseur de patacrep pour lire les infos des chants. Je ne sais pas encore si ça restera comme ça. Comme dit à l'instant autre part, je n'aime pas la multiplication des outils pour faire la même chose, et j'ai voulu réutiliser l'existant. Je ne le sens pas encore complètement.

Jetez un oeil sur les modifs de modèles et dites moi ce que vous en pensez. Et bien sûr tout ce que vous voyez.

**Comment by Luthaf** [comment]
Cool, ça avance plus vite que prévu ce projet =)

Il y a des bouts de ton code que je ne comprend pas : 

```
git = sh.git.bake(_cwd=settings.SONGS_LIBRARY_DIR)
filerev = git("rev-parse", "HEAD")
```
- Tu te sert de sh.git pour intéragir avec git ? 
- Pour la partie 

```
language_model = models.Language.objects.get(language_name)
```

Pourquoi ne pas faire un get_or_create plutôt ?
- Il ne manque que la partie GitFile du modèle Song, c'est ça ?
- Je ne suis pas sur que `unique=True`soit nécessaire pour un modèle OneToOne
- Au passage, ton code me fait penser qu'il manque les docstrings au mien ...
- Pour le modèle GitFile, ou le modèle Song on pourrai ajouter la date de création, la date de dernière modification et la personne à l'origine de la dernière modification.

**Comment by jmclem** [comment]
> Tu te sert de sh.git pour intéragir avec git

En fait, j'utilise le module sh (`pip install sh`) qui permet d'encapsuler des appels système, et je l'utilise pour git.

`get_or_create`: je connaissais pas, c'est un bon indice

> Je ne suis pas sur que unique=Truesoit nécessaire pour un modèle OneToOne

T'as sans doute raison ;)

> Il ne manque que la partie GitFile du modèle Song, c'est ça ?

en très gros, oui, puis un peu de crash test.
J'y ajouterai ensuite le cache des textes de chansons sous forme de fichiers, à moins qu'il n'y ait d'autres choses plus importantes.

**Comment by Luthaf** [comment]
> le cache des textes de chansons sous forme de fichiers

Tu parle du cache HTML pour l'affichage ?

**Comment by jmclem** [comment]
Just committed my state of the changes. See the [README.md](https://github.com/Luthaf/songbook-web/blob/3f4fa49f6b69b6c3e850d066f327e54545d8eb64/README.md) for set up and importing directly from the songbook repo. It just does what the issue says : "Parsing song files from a tree and fill db with information", no more... Give it a try and tell me; I successfully imported the whole songbook (takes a couple of minutes ;) ) and could navigate it in the browser thanks to the web views:
![songbook-with-songs](https://f.cloud.github.com/assets/721746/2014544/3e18f582-87a6-11e3-8e3b-64fde14cf7f1.jpg)

**Comment by oliverpool** [comment]
I have some hard time with PlasTeX...
This is what I have done:
1. Install plasTeX (might exist in repo : python-plastex)
2. clone songbook repo and checkout to "next"
3. copy PyTexSongs to songbook and rename it to utils
4. pip install sh
5. change the repo in settings.py to select the songs folder of the songbook-web folder
6. Make sure to have Django 1.6 (or AttributeError: 'module' object has no attribute 'atomic')

And then it works !!!!
Really nice job :+1: !

**Comment by oliverpool** [comment]
Small bug : 
la_jument_de_michao.sg defines the Artiste as {Tri\ Yann} => the '\' creates 2 differents artists (TriYann and TriYann)

Where is the error?
- the file should not contain such thing : "\ "
- parsetex should clean it
- importsong should handle it 
  (maybe a title with "~" might cause some problems too)

**Comment by jmclem** [comment]
Glad it works for you too :)

As for Tri\ Yann : I had this too, but I'd say the file content is faulty and should be corrected, or is there any reason for this backslash here ?

Else : I would expect parsetex to handle this. It does it properly for a song from Britney Spears (britney_spears/baby_one_more_time.sg) reading : `\beginsong{\dots~Baby one more time}`. The `\dots` gets removed (well, I guess/hope from parsetex)

**Comment by jmclem** [comment]
> copy PyTexSongs to songbook and rename it to utils

what do you mean here?

**Comment by Luthaf** [comment]
>  copy PyTexSongs to songbook and rename it to utils

In my version of the 'next' branch, I've renamed the utils module to PyTeXSong. That was mainly a test, for the core/library separation of the songbook data. It may or not go on this way, depends on the others evolutions. I think I will put all this in another branch.

**Comment by jmclem** [comment]
Since it works for Luthaf too, I close this and propose to address bugs and further devs through new issues.

**Comment by Luthaf** [comment]
Juste au passage, bravo pour ton boulot ! C'est le bout que j'attendais avant de pouvoir terminer l'ajout des chants dans les carnets =)

**Comment by jmclem** [comment]
Merci, je suis impatient de voir la suite :) !

**Comment by oliverpool** [comment]
On pourrait peut-être inclure le fichier plastex.py dans le project songbook-web ?
(il est relativement indépendant du compilateur TeX)

**Comment by Luthaf** [comment]
Oui, en effet, si on ajoute une mention de provenance du fichier =)

**Comment by jmclem** [comment]
Oui ; ttfs, s'il reste utilisé dans 'sonbook', n'est ce pas plutôt là qu'il faudrait le mettre ?

**Comment by Luthaf** [comment]
Ça dépend : est-ce que l'on met le moteur de compilation LaTeX comme sous-dossier du projet `generator` ? Je suis assez pour en fait, vu que ce projet ne peut pas fonctionner sans. Et comme ça on a plus de problème de modules non trouvés =)

EDIT : je viens de voir qu'il existait des sous-modules avec git, ça pourrait faire l'affaire, non ?

**Comment by jmclem** [comment]
Hmmm; la question est intéressante et en lève une autre : quelle collaboration est prévue à l'avenir pour les deux projets songbook et songbook-web? Nous acheminons nous vers quelquechose comme 
![533d6c68](https://f.cloud.github.com/assets/721746/2019128/1bf2542c-881d-11e3-821b-c0e5cbf03e53.png)
(éditer ici : http://www.yuml.me/edit/533d6c68 )?
Si oui, alors je ferais
- une repo spécifique pour les chants, sans moteur ni rien
- et ensuite 
  - soit une repo avec tout (moteur, desktop et web)
  - soit trois repos, une pour chaque package.

**Comment by Luthaf** [comment]
Comment je vois le bazar : 

![songbook](https://f.cloud.github.com/assets/6141587/2021107/30f61b5c-883a-11e3-9deb-363ae7baa78e.png)

NB : je ne connais pas la vrai signification des diagrammes UML, donc il y a peut-être des erreurs, mais c'est l'idée qui compte.
NB2 : Je n'ai pas réussi à utiliser ce site web, du coup j'ai récupéré ArgoUML pour faire ce diagramme. Je peut mettre les sources si besoin.

Du coup je suis pour 4 repos : 
- Les chants
- L'interface Qt
- L'interface Web
- Le backend Python/LaTeX

**Comment by oliverpool** [comment]
je suis assez d'accord avec 3 types repos:
- un pour le backend (les quatre "bulles" centrales en losange)
- un pour chacune des interfaces (Qt, Web...)
- plusieurs pour les chants (celui de Lohrun pour patacrep, un pour le site-web...)

(ce qui fait plutôt 5 repos, car je ne pense pas qu'on mélange les repos de Lohrun et celui du site web)

**Comment by jmclem** [comment]
Je penche aussi pour une repo par projet et une pour chaque collection de chants

**Comment by oliverpool** [comment]
Et les fichiers .sb n'ont pas besoin de repo à mon avis (on peut proposer de les télécharger en format brut à la limite)

**Comment by Luthaf** [comment]
Ok, je vais ajouter le moteur Python/LaTeX comme sous-module du projet web alors :)

EDIT : Fait !

**Comment by Luthaf** [comment]
Pour la question de la séparation moteur/données, la discution a lieu en parallèle sur le [forum](http://www.patacrep.com/forum/viewtopic.php?id=69) Patracrep.
