### ISSUE TITLE
Passer à Django 1.7 avant le déploiement

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#81]
Django 1.7 RC1 vient de sortir le 26/06. Je pense qu'il serait bien de passer à cette version qui nous permet de virer South en apportant les même fonctionnalité. Mais surtout, il faudrait le faire avant le déploiement.

Qu'en pensez-vous ?

**Comment by oliverpool** [comment]
Je suis assez favorable ! (je crois que je n'ai jamais réussi à faire fonctionner south correctement...)

PS : je risque d'avoir du temps dans les jours qui viennet :-)

**Comment by Luthaf** [comment]
> je crois que je n'ai jamais réussi à faire fonctionner south correctement..

C'est à présent intégré à Django, mais pas beaucoup plus simple à utiliser de ce que j'en ai vu ...

> PS : je risque d'avoir du temps dans les jours qui viennent :-)

Cool ! Si tu peut repasser derrière moi sur le CSS, j'ai bricolé un truc mais c'est moche et pas fluide du tout.

**Comment by Luthaf** [comment]
Bon, ça fait 2 semaines que je tourne avec la 1.7 rc1, et rien à signaler. Donc je pense que l'on pourra l'utiliser dès la sortie officielle (qui ne devrais pas tarder ^^).

**Comment by Luthaf** [comment]
Elle a un peu tardé, mais elle est là !

https://www.djangoproject.com/weblog/2014/sep/02/release-17-final/

Je passe mon serveur sous 1.7 et je fait quelques commits de mise à jour avant de fermer ici. Pour mettre à jour vos bases de donnée en local, il y a des instructions [ici](https://docs.djangoproject.com/en/1.7/topics/migrations/#upgrading-from-south)
