### ISSUE TITLE
Erreur 404 lors du changement de slug d'une chanson

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#83]
Lorsque l'utilisateur édite le titre d'une chanson et que cela change le slug, l'url de redirection contient l'ancien slug (ce qui provoque une erreur 404).

[Mes compétences en python/django sont trop faibles pour corriger ce bug rapidement...]

**Comment by Luthaf** [comment]
> Lorsque l'utilisateur édite le titre d'une chanson et que cela change le slug, l'url de redirection contient l'ancien slug (ce qui provoque une erreur 404).

Merci du retour !

> [Mes compétences en python/django sont trop faibles pour corriger ce bug rapidement...]

Chacun ses compétences : je suis mauvais en JS, et en design.
