### ISSUE TITLE
Impossible de renommer les sections déjà insérée dans le carnet

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#86]
Une fois les sections insérées, le renommage dans le formulaire HTML n'est pas répercuté dans la BDD

**Comment by oliverpool** [comment]
Je vois deux possibilités d'implémentation:
- soit on rajoute un champ (caché) avec le titre initial de la section. Lors du POST, si les deux valeurs sont différentes, on met à jour la ligne de BDD
- soit on compare aux valeurs en BDD

**Comment by Luthaf** [comment]
J'allais m'y mettre, et je pensais prendre cette implémentation :  

> soit on compare aux valeurs en BDD

**Comment by oliverpool** [comment]
Ok
