### ISSUE TITLE
Les noms des sections ne sont pas vérifiés (caractères Latex interdits)

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patanet#93]
Insérer des caractères spéciaux dans les noms de fonction fait planter la génération de PDF.

Je pense qu'il faudrait utiliser la fonction [_clean_latex](/patacrep/patanet/blob/master/generator/forms.py#L163), mais je ne vois pas comment faire un truc propre (et idiomatique à Python)...

Deux appels nécéssaires:
- [ajout d'une section](/patacrep/patanet/blob/master/generator/views/songbooks.py#L274)
- [modification du nom d'une section](/patacrep/patanet/blob/master/generator/views/songbooks.py#L291)

**Comment by Luthaf** [comment]
L'idée est d'échapper les caractères pour qu'ils apparaissent, ou de les interdire avec un message ? 

Le problème dans ce cas est que nous devrons gérer nous même la validation des formulaires, étant donné que nous n'utilisons pas les formulaires Django.

**Comment by oliverpool** [comment]
Je verrai bien le même comportement que pour le titre et la description : les interdire avec un message

**Comment by Luthaf** [comment]
Je viens de faire un quick fix pour ce problème, c'est très loin d'être optimal, mais c'est tout ce que je peut faire pour le moment. 

Il faudrait globalement revoir l'architecture pour les ajouts/modification d'éléments d'un carnet, ça permettrai d'utiliser un formulaire (ou mieux, un formset) pour gérer les erreurs.

**Comment by oliverpool** [comment]
Lors de la refactorisation de `move_or_delete_items` (issue #111), j'en ai profité pour rajouter une validation des noms de section.
Je push le tout sous peu
