### ISSUE TITLE
Diffusion de paroles vs Droit d'auteur ???

### ISSUE THREAD

**Issue by Soundy25** [patacrep/patanet#97]
Bonjour à tous.
La mention affichée dans la section footer du site me pose question : 

<< Ce recueil de chansons n'a absolument aucune vocation commerciale et joue sur l'autorisation tacite des auteurs et des ayants droits, pensant que la publication de ces tablatures représente plutôt une publicité positive à leur égard.[...] >>

A quelle "autorisation tacite" faites-vous référence ?
En fait, les paroles des chansons sont, au même titre que la musique, protégées par le droit d'auteur. Sans autorisation écrite de la part de l'auteur, on n'est pas censé diffuser les textes...

Sans vouloir miner qui que ce soit, je me documente depuis hier sur ce point et ce que je trouve n'est pas très encourageant, voici quelques url : 
http://www.nextinpact.com/archive/66936-parolesnet-partitions-chanson-texte-fans.htm 
http://www.01net.com/editorial/265222/les-sites-de-paroles-de-chansons-reduits-au-silence/
http://junon.u-3mrs.fr/u3ired01/Main%20docu/PLA/chron-contrefa%8Don.pdf   (très instructif)
http://www.presse-citron.net/greatsong-net-premier-site-legal-pour-la-diffusion-de-paroles-de-chansons/ 

Je suis en contact avec un ami juriste du multimédia (j'ai une entière confiance en sa discrétion) et j'essaie de voir si c'est contournable, mais voici ce qu'il me dit :  
<< soit le contenu est dans le domaine public (70 ans après la mort de l'auteur), soit le contenu ne peut pas être utilisé sans autorisation, même si on ne le revend pas. C'est ce que l'on appelle la contrefaçon. Les amendes sont énormes et la prison n'est pas rare.>>
...ce qui colle pas mal avec les infos collectées sur les sites ci-dessus, même si elles datent un peu.

Je ne sais pas si l'EDITEUR peut se dédouaner au prétexte qu'il ne fournit qu'un service et, dans ce cas d'espèce, les contenus seraient postés par les UTILISATEURS sous leur entière responsabilité. 
Si l'éditeur du site se place comme fournisseur de service uniquement, je ne pense pas qu'il soit attaquable [à vérifier], mais le pb c'est que dans l'offre actuelle, vous proposez de contenus protégés qui ne vous appartiennent pas... 

Donc, toujours sans vouloir miner personne, que pensez-vous de ceci et quelle est votre position là-dessus ?

**Comment by Luthaf** [comment]
On en avait deja discute dans cette issue : #16. 

La distinction editeur/utilisateur est utilisee par quelques autres sites, a voir si on peut s'appuyer dessus aussi.

Pour le reste, je reviendrai plus tard.

**Comment by Soundy25** [comment]
Ok, je vois que le pb est cerné.  
<i>Désolé, je n'ai pas lu tous les sujets...</i>

Je poursuis en vérifiant que l'EDITEUR peut (ou pas ?) se cacher derrière l'UTILISATEUR/POSTEUR.
Un peu comme le bon coin qui n'est pas responsable juridiquement des contenus affichés sur leur service. [à vérifier]

Que pensez-vous de cette option ?

**Comment by Soundy25** [comment]
CGU Bon coin (LCB France)
http://www2.leboncoin.fr/dc/cgu/0 

ARTICLE 3 : UTILISATION DU SERVICE LEBONCOIN
3.2 Diffusion des Annonces
3.2.2 Engagement de l'Annonceur
[Extraits]

L'Annonceur garantit détenir tous les droits (notamment des droits de propriété intellectuelle) ou avoir obtenu toutes les autorisations nécessaires à la publication de son Annonce.

L'Annonceur garantit que l'Annonce ne contrevient à aucune réglementation en vigueur (notamment relatives à la publicité, à la concurrence, à la promotion des ventes, à l'utilisation de la langue française, à l'utilisation de données personnelles, à la prohibition de la commercialisation de certains biens ou services), ni aucun droit de tiers (notamment aux droits de propriété intellectuelle et aux droits de la personnalité) et qu'il ne comporte aucun message diffamatoire ou dommageable à l'égard de tiers.

Ainsi, l'Annonceur s'engage notamment à ce que l'Annonce ne contienne :
    aucune mention diffamatoire ou de nature à nuire aux intérêts et/ou à l'image de LBC France ou de tout tiers.
    aucun contenu portant atteinte aux droits de propriété intellectuelle de tiers.
    aucun contenu à caractère promotionnel ou publicitaire en lien avec l'activité de l'Annonceur. En effet, une Annonce est destinée à promouvoir un produit et n'est pas un support de publicité

Dans ce cadre, l'Annonceur déclare et reconnaît qu'il est seul responsable du contenu des Annonces qu'il publie et rend accessibles aux Utilisateurs, ainsi que de tout document ou information qu'il transmet aux Utilisateurs.

En conséquence, l'Annonceur relève LBC FRANCE, ses sous-traitants et fournisseurs, de toutes responsabilités, les garantit contre tout recours ou action en relation avec l'Annonce qui pourrait être intenté contre ces derniers par tout tiers, et prendra à sa charge tous les dommages-intérêts ainsi que les frais et dépens auxquels ils pourraient être condamnés ou qui seraient prévus à leur encontre par un accord transactionnel signé par ces derniers  avec ce tiers , nonobstant tant tout dommages-intérêts dont LBC France, ses sous-traitants et fournisseurs pourraient réclamer à raison des faits dommageables de l’Annonceur.

En déposant toute Annonce, chaque Annonceur reconnaît et accepte que LBC France puisse supprimer, à tout moment, sans indemnité ni droit à remboursement des sommes engagées par l'Annonceur aux fins de son dépôt ou de la souscription à des Options Payantes, une Annonce qui serait contraire notamment à la loi française, aux règles de diffusion du Service LEBONCOIN fixées par LBC France et accessibles ici et/ou susceptible de porter atteinte aux droits de tiers.
